// Project facts and résumé records. Case-study prose is authored from intake, not lifted.
window.PORTFOLIO = {
  identity: {
    name: "Caleb Stacy",
    title: "Senior content designer",
    differentiator: "Language systems · content engineering",
    thesis: "I build the standards and the checks that hold a product's language to a target instead of an adjective.",
    location: "Richmond, Virginia · Local + remote",
  },
  projects: [
    {
      id: "verso", number: "01", title: "Verso",
      context: "AI content governance · Meta · 2025–2026",
      statement: "Voice was written in adjectives. I turned it into a target an agent could be held to.",
      summary: "Meta's content design org was being asked to move from in the loop to on the loop: to govern what agents wrote instead of writing it. I built Verso: a content agent that measures its own draft against a product's real voice and corrects itself before a human sees it.",
      outcomeLabel: "Results",
      results: ["Adopted by content designers across Meta by word of mouth", "Five product surfaces fingerprinted from their real strings", "Handed to central content design, and still in use"],
      role: "Sole creator — the agent, the measurement engine, and the index",
      team: "Solo build · partnered with central content design to adopt it",
      timeline: "2025–2026",
      surface: "Meta's internal content tooling, company-wide",
      teamSurface: "Solo, on Meta's internal infrastructure. I partnered with central content design to adopt it, and they own it now.",
      character: "assets/work/caleb-verso-workstation-fixed.png",
      characterAlt: "Clay Caleb working at a large computer",
      artifacts: [
        { src: "assets/work/verso-evidence-cabinet.png", alt: "Clay render of a card-index cabinet holding filed evidence", label: "The index, as an object", caption: "A rendered stand-in for the index: each surface gets its own drawer, and each measurable dimension its own card. No internal Meta material, index values, or product strings are shown." },
        { src: "assets/work/card-verso.jpg", alt: "Prototype screen showing a deterministic pass and a voice-shape radar", label: "Public-safe prototype", caption: "A prototype of the instrument: the deterministic pass on the left, the voice shape as a radar of the measured dimensions on the right. Built for portfolio use. The values shown are not Meta's." },
      ],
      sources: ["Central brand guidance", "Product-area guidance", "Docs, chats, and spreadsheets", "Real shipped strings"],
      ledger: [{ value: "11", label: "Measured dimensions" }, { value: "5", label: "Surfaces fingerprinted" }, { value: "6 mo", label: "Solo build" }, { value: "500+", label: "Agent conversations" }],
      pipeline: ["Ingest the real shipped strings of a product surface.", "Fingerprint the corpus across eleven measurable dimensions.", "Serve it warm, so measurement is cheap enough to call on every draft.", "The agent measures its own draft and adjusts until it lands inside the deviation."],
      quote: "“Be concise” names something the reader feels. It does not name anything the writer did.",
      quoteBy: "The receiver-side problem",
    },
    {
      id: "vr-education", number: "02", title: "First-time VR",
      context: "New-user education · Meta Horizon · 2025",
      statement: "Find the fun first. Teach in the moment.",
      summary: "New users came to socialize, but Horizon asked them to choose a world, consent, complete fourteen-plus lessons, and wait through loading before they met anyone. I partnered with the product designer to replace the curriculum with a just-in-time education strategy.",
      outcomeLabel: "Results",
      results: ["+29% onboarding completion", "+20% weekly active use", "+7% new-user retention"],
      role: "Content designer · education strategy and interaction language",
      team: "With a product designer · 1 PM · 3 engineers · 5 partner teams",
      timeline: "2025",
      surface: "Meta Horizon Worlds, first-run VR",
      teamSurface: "With a product designer · 1 PM · 3 engineers · 5 partner teams · Meta Horizon Worlds, first-run VR",
      character: "assets/work/caleb-vr-cutout.png",
      characterAlt: "Clay Caleb in a VR headset, controllers in hand",
      artifacts: [],
      evidenceNote: "The measured lifts are on the cover and the education strategy is stated in full above. The first-run sequence itself stays unpublished because the captures belong to Meta. A rebuilt approximation of an onboarding flow would be the one thing this document refuses to do: present a reconstruction as the experiment.",
      sources: ["World selection", "Recording consent", "Fourteen-plus lessons", "Starter world loading"],
      ledger: [{ value: "72%", label: "Original drop-off" }, { value: "15 min", label: "Original onboarding" }, { value: "90 s", label: "Of loading" }, { value: "14+", label: "Lessons before play" }],
      pipeline: ["Teach one action on the input that needs it.", "Reinforce in context when state changes.", "Nudge on the controller, not in a modal.", "Never replay the syllabus."],
      quote: "Stop teaching everything once. Teach one action, in the moment it matters.",
      quoteBy: "Education strategy principle",
    },
    {
      id: "horizon", number: "03", title: "Horizon mobile",
      context: "Mobile product strategy · Meta Horizon · 2024",
      statement: "Giving people a reason to open Horizon on their phone.",
      summary: "I owned content design for Meta Horizon mobile's first loop built to bring people back. A discovery moment led to a choice. The choice produced visible progress. Progress earned a reward, and the reward gave someone an actual reason to open the app again.",
      outcomeLabel: "Results",
      results: ["Feed units lifted 28-day retention by about 15%", "Quests homepage grew daily actives by nearly 5%", "Core loop proved as a mobile retention driver"],
      role: "Lead content designer, mobile retention",
      team: "Product and design",
      timeline: "2024",
      surface: "iOS and Android",
      teamSurface: "Product + Design · iOS and Android",
      character: "assets/work/caleb-horizon-headset.png",
      characterAlt: "Clay Caleb examining a VR headset",
      artifacts: [
        { src: "assets/work/horizon-app-montage.png", alt: "Three shipped Horizon mobile screens", label: "Shipped surfaces", caption: "Profile, feed, and device management as they shipped on mobile. Not the exact experiment surface." },
        { src: "assets/work/horizon-profile-ui.png", alt: "Horizon mobile profile screen", label: "Identity and profile", caption: "The profile surface the identity and progress work landed on." },
      ],
      sources: ["Quests homepage", "Feed hypotheses", "Identity and profile", "Social context", "Safety surfaces", "Rewards"],
      ledger: [{ value: "5", label: "Reusable jobs" }, { value: "2", label: "Experiment families" }, { value: "iOS + Android", label: "Surfaces" }, { value: "+15%", label: "28-day retention" }],
      pipeline: ["Discover: the phone can start the loop.", "Choose: one clear next thing.", "Progress: visible and honest.", "Reward: earned in play, not in the feed.", "Return: a real reason, not a badge."],
      quote: "The phone can start the loop. Play stays the destination.",
      quoteBy: "Mobile product principle",
    },
    {
      id: "portals", number: "04", title: "Portals",
      context: "Spatial interaction · Meta Horizon · 2024",
      statement: "Designing navigation when the interface is the space.",
      summary: "I turned proximity into an information architecture: identity at a distance, actions when someone showed interest, and the full decision context only when they moved close enough to need it.",
      outcomeLabel: "What changed",
      outcomeProse: "The work increased portal engagement, improved retention, earned VP alignment, shipped in Horizon, and was introduced by Mark Zuckerberg at Meta Connect 2024.",
      role: "Content design lead",
      team: "Product, Engineering, UXR, and Design",
      timeline: "2024",
      surface: "Spatial navigation in Meta Horizon",
      teamSurface: "Product, Engineering, UXR, and Design · spatial navigation in Meta Horizon",
      character: "assets/work/caleb-portals-threshold.png",
      characterAlt: "Clay Caleb stepping through a portal",
      artifacts: [
        { src: "assets/work/card-portals.jpg", alt: "A portal card showing a world, who is inside, and one action", label: "Shipped surface", caption: "A portal at approach distance: identity, who is already inside, and the one available action." },
        { src: "assets/work/card-portals-keynote.jpg", alt: "Frame from the Meta Connect 2024 keynote", label: "Public source", caption: "Introduced at Meta Connect 2024. Frame from the public keynote." },
      ],
      sources: ["Identity at a distance", "Social context", "Available action", "Full decision context"],
      ledger: [{ value: "3", label: "Disclosure distances" }, { value: "A/B", label: "Tested with UXR" }, { value: "Connect 2024", label: "Public reveal" }, { value: "Shipped", label: "In Horizon" }],
      pipeline: ["At distance, show identity only.", "On interest, add the available action.", "On approach, reveal the full decision context.", "Never show maximum entries at once."],
      quote: "State of intent, not maximum entries.",
      quoteBy: "Spatial IA principle",
    },
    {
      id: "word-math", number: "05", title: "Word Math",
      context: "Independent research · May 2026",
      statement: "Measuring what voice guides leave vague.",
      summary: "I built a voice-measurement engine that scores text on twelve checkable dimensions, then ran four hundred Claude generations through it to find out whether numeric, form-side guidance actually beats a published voice guide at shaping what a model writes.",
      outcomeLabel: "Results",
      results: ["400 controlled generations", "12 measured dimensions", "Constraints moved output"],
      role: "Creator and researcher",
      timeline: "May 2026",
      surface: "Python engine",
      teamSurface: "Independent research · Python engine · 12 dimensions · 400 generations",
      character: "assets/work/word-math-counting-words.jpg",
      characterAlt: "Clay Caleb in a lavender suit at a casino, counting words the way Alan counts cards, equations floating past his face",
      artifacts: [],
      evidenceNote: "Word Math is independent research: the evidence is the measurements themselves, in the table above. There is no product surface to show, and an illustration of one would add nothing a number does not already say.",
      sources: ["Naive prompt", "Published voice guide", "Numerical constraints", "Numerical plus English"],
      ledger: [{ value: "400", label: "Generations" }, { value: "12", label: "Dimensions" }, { value: "4", label: "Conditions" }, { value: "Sonnet 4.6", label: "Model tested" }],
      pipeline: ["Numbers control surface features.", "English descriptions still shape composition.", "Deterministic checks beat prose where both apply.", "Model judgment comes last."],
      quote: "Numbers controlled surface features. English still mattered for composition.",
      quoteBy: "Selected finding",
    },
  ],
  chapters: [
    { id: "overview", label: "Overview" }, { id: "problem", label: "Problem" },
    { id: "reframe", label: "Reframe" }, { id: "decisions", label: "Decisions" }, { id: "proof", label: "Proof" },
  ],
  contact: "calebstacy@gmail.com",
  resumeSummary: "Twelve years working with language under pressure: classrooms and Army briefing rooms, then games and virtual worlds at Meta scale, with detours through health and enterprise software. I look for the language decisions a system can measure or enforce, and keep the remaining judgment with people.",
  experience: [
    {
      when: "November 2022 – May 2026", org: "Meta", role: "Senior content designer · Horizon, experimentation, and AI · Reality Labs and cross-org",
      bullets: [
        "Created Meta's content-standards infrastructure. Built Verso, the company's first domain-specific AI CD, and the platform to power it: a deterministic lint toolkit, an eleven-dimension measurement engine with per-product voice baselines computed from shipped strings, and a structured index of terminology rules, review blockers, and measurement profiles covering product surfaces including Instagram, Facebook, Messenger, WhatsApp, Quest, and Horizon.",
        "Led travel terminology across Meta Horizon OS — one vocabulary for calling, sessions, and travel across VR, mobile, and desktop surfaces — and the naming audit for the Meta Quest to Horizon OS re-brand.",
        "Established Meta Horizon's first content experimentation practice and led content designers across its major product areas, representing the org. Built the workshops and the working tools for writing hypotheses and tracking tests.",
        "Brought content designers into agentic workflows through workshops and office hours. Taught local agent setup in VS Code, then helped designers author their own reusable skill files and deterministic scripts for the rules prose guidance could never reliably enforce.",
        "Helped turn the Meta Horizon phone app from a headset utility into a repeat-use mobile product. I led content from the early journeys and a strategy one-pager written for Zuck through the launch experiments; the feed experiment lifted 28-day retention by about 15%, and the quests homepage grew daily actives by nearly 5% in its first test.",
        "Defined the strategy and jobs to be done for Horizon portals, including the metadata and progressive-disclosure framework for moving between virtual worlds. Earned VP alignment and appeared in the Meta Connect 2024 keynote.",
        "Replaced billboard-style instruction with just-in-time spatial education: controllers and spatial cues teaching one thing at the moment it became relevant. Improved first-world visits, onboarding completion, and retention. The strategy and components were adopted by the Meta Quest onboarding team.",
      ],
    },
    {
      when: "October 2021 – October 2022", org: "Digbi Health", role: "Lead UX writer",
      bullets: [
        "Led product content for a precision-health startup, turning microbiome science and clinical data into personalized journeys from onboarding through behavior change. Genetics were included, and every journey stayed legible to a member with no clinician beside them.",
      ],
    },
    {
      when: "April – October 2021", org: "8x8", role: "UX writer",
      bullets: [
        "Made enterprise voice, video, chat, and contact-centre tools understandable, including the phone administration the business owners setting it up had to get through.",
      ],
    },
    {
      when: "2014 – 2021", org: "WVU, VCU, and Army Logistics University", role: "Professor",
      bullets: [
        "Taught composition and poetry workshops to university writers, then trained Army officers to turn complex, high-stakes information into clear, direct language. Seven years of watching what makes writing land, which is where the rest of this comes from.",
      ],
    },
  ],
  resume: [
    { org: "Meta", role: "Senior content designer · Horizon, experimentation, and AI", when: "November 2022 – May 2026" },
    { org: "Digbi Health", role: "Lead UX writer", when: "October 2021 – October 2022" },
    { org: "8x8", role: "UX writer", when: "April – October 2021" },
    { org: "WVU, VCU, and Army Logistics University", role: "Professor", when: "2014 – 2021" },
  ],
  education: [
    { org: "Virginia Commonwealth University", role: "MFA, Poetry", when: "2018" },
    { org: "West Virginia University", role: "BA, English", when: "2014" },
  ],
  tools: ["Content design", "Early product strategy", "Content systems", "Taxonomy design", "Terminology schemas", "Deterministic content checks", "Experiment design", "Agent and skill authoring", "AI workflow design", "MCP", "Game and social UX", "Spatial UX", "Trust and safety", "Workshop facilitation", "Python", "JavaScript", "HTML and CSS", "Figma", "VS Code", "GitHub"],
  publicWork: [
    {
      title: "Word Math",
      body: "An open engine that decomposes writing into twelve computable dimensions, turns a target profile into generation constraints, then validates the result; ships a skill that teaches any coding agent to lint its own prose. github.com/calebstacy/word-math",
    },
    {
      title: "Working papers",
      body: "A running list of short public studies on measuring and governing product language. calebstacy.com/papers",
    },
    {
      title: "slop-no-more",
      body: "A deterministic scanner for the rhetorical moves that make prose read as machine-written: a 26-family catalog, severity tiers and repair rules.",
    },
  ],
};
