// Project facts and résumé records. Case-study prose is authored from intake, not lifted.
window.PORTFOLIO = {
  identity: {
    name: "Caleb Stacy",
    title: "Senior content designer",
    differentiator: "Product strategy · interaction language",
    thesis: "I shape complex products from early direction through interaction language and experiments. Then I turn the decisions worth repeating into systems people — and agents — can use.",
    location: "Richmond, Virginia · Local + remote",
    site: "calebstacy.com",
  },
  projects: [
    {
      id: "verso", number: "01", title: "Verso",
      context: "AI content governance · Meta · 2025–2026",
      subPages: [
        { id: "verso/agent", label: "Agent" },
        { id: "verso/engine", label: "Engine" },
        { id: "verso/index", label: "Index" },
      ],
      statement: "Voice was written in adjectives. I turned it into a target an agent could be held to.",
      summary: "Meta's content design org was being asked to move from in the loop to on the loop: to govern what agents wrote instead of writing it. I built Verso: a content agent that measures its own draft against a product's real voice and corrects itself before a human sees it.",
      outcomeLabel: "Results",
      results: ["Adopted by content designers across Meta by word of mouth", "Five product surfaces fingerprinted from their real strings", "Handed to central content design, and still in use"],
      role: "Sole creator — the agent, the measurement engine, and the index",
      team: "Solo build · partnered with central content design to adopt it",
      timeline: "2025–2026",
      surface: "Meta's internal content tooling, company-wide",
      teamSurface: "Solo, on Meta's internal infrastructure. I partnered with central content design to adopt it, and they own it now.",
      character: "assets/work/caleb-verso-workstation-fixed.png",
      characterAlt: "Clay Caleb working at a large computer",
      artifacts: [
        { src: "assets/work/verso-evidence-cabinet.png", alt: "Clay render of a card-index cabinet holding filed evidence", label: "The index, as an object", caption: "A rendered stand-in for the index: each surface gets its own drawer, and each measurable dimension its own card. No internal Meta material, index values, or product strings are shown." },
      ],
      sources: ["Central brand guidance", "Product-area guidance", "Docs, chats, and spreadsheets", "Real shipped strings"],
      ledger: [{ value: "11", label: "Measured dimensions" }, { value: "5", label: "Surfaces fingerprinted" }, { value: "6 mo", label: "Solo build" }, { value: "500+", label: "Agent conversations" }],
      pipeline: ["Ingest the real shipped strings of a product surface.", "Fingerprint the corpus across eleven measurable dimensions.", "Serve it warm, so measurement is cheap enough to call on every draft.", "The agent measures its own draft and adjusts until it lands inside the deviation."],
      quote: "“Be concise” names something the reader feels. It does not name anything the writer did.",
      quoteBy: "The receiver-side problem",
    },
    {
      id: "vr-education", number: "02", title: "VR NUX",
      context: "New-user education · Meta Horizon · 2025",
      statement: "Find the fun first. Teach in the moment.",
      summary: "New users came to socialize, but Horizon asked them to choose a world and consent to recording. Then they had to complete fourteen-plus lessons and wait through loading before they met anyone. I led the education strategy and interaction language across the product team, design team, three engineers and five partner teams to replace that curriculum with just-in-time education.",
      outcomeLabel: "Results",
      results: ["+29% onboarding completion", "+20% weekly active use", "+7% new-user retention"],
      role: "Content designer · education strategy and interaction language",
      team: "Product · Design · 3 engineers · 5 partner teams",
      timeline: "2025",
      surface: "Meta Horizon Worlds, first-run VR",
      teamSurface: "Product · Design · 3 engineers · 5 partner teams · Meta Horizon Worlds, first-run VR",
      character: "assets/work/caleb-vr-cutout.png",
      characterAlt: "Clay Caleb in a VR headset, controllers in hand",
      artifacts: [],
      evidenceNote: "The measured lifts are on the cover and the education strategy is stated in full above. The first-run sequence itself stays unpublished because the captures belong to Meta. A rebuilt approximation of an onboarding flow would be the one thing this document refuses to do: present a reconstruction as the experiment.",
      sources: ["World selection", "Recording consent", "Fourteen-plus lessons", "Starter world loading"],
      ledger: [{ value: "72%", label: "Original drop-off" }, { value: "15 min", label: "Original onboarding" }, { value: "90 s", label: "Of loading" }, { value: "14+", label: "Lessons before play" }],
      pipeline: ["Teach one action on the input that needs it.", "Reinforce in context when state changes.", "Nudge on the controller, not in a modal.", "Never replay the syllabus."],
      quote: "Stop teaching everything once. Teach one action, in the moment it matters.",
      quoteBy: "Education strategy principle",
    },
    {
      id: "portals", number: "03", title: "Horizon Portals",
      context: "Spatial interaction · Meta Horizon · 2024",
      statement: "Designing navigation when the interface is the space.",
      summary: "I turned proximity into an information architecture: identity at a distance, actions when someone showed interest, and the full decision context only when they moved close enough to need it.",
      outcomeLabel: "What changed",
      outcomeProse: "The work increased portal engagement, improved retention, earned VP alignment, shipped in Horizon, and was introduced by Mark Zuckerberg at Meta Connect 2024.",
      role: "Content design lead",
      team: "Product, Engineering, UXR, and Design",
      timeline: "2024",
      surface: "Spatial navigation in Meta Horizon",
      teamSurface: "Product, Engineering, UXR, and Design · spatial navigation in Meta Horizon",
      character: "assets/work/caleb-portals-threshold.png",
      characterAlt: "Clay Caleb stepping through a portal",
      heroVideo: "assets/work/portals-connect-hero.mp4",
      heroPoster: "assets/work/portals-connect-poster.jpg",
      heroCaption: "Meta Connect 2024. Mark Zuckerberg introduces the portal experience on stage.",
      artifacts: [
        { src: "assets/work/card-portals.jpg", alt: "A portal card showing a world, who is inside, and one action", label: "Shipped surface", caption: "A portal at approach distance: identity, who is already inside, and the one available action." },
      ],
      sources: ["Identity at a distance", "Social context", "Available action", "Full decision context"],
      ledger: [{ value: "3", label: "Disclosure distances" }, { value: "A/B", label: "Tested with UXR" }, { value: "Connect 2024", label: "Public reveal" }, { value: "Shipped", label: "In Horizon" }],
      pipeline: ["At distance, show identity only.", "On interest, add the available action.", "On approach, reveal the full decision context.", "Never show maximum entries at once."],
      quote: "State of intent, not maximum entries.",
      quoteBy: "Spatial IA principle",
    },
  ],
  chapters: [
    { id: "overview", label: "Overview" }, { id: "problem", label: "Problem" },
    { id: "reframe", label: "Reframe" }, { id: "decisions", label: "Decisions" }, { id: "proof", label: "Proof" },
  ],
  contact: "calebstacy@gmail.com",
  resumeSummary: "Senior content designer who builds language systems: measurable voice standards, terminology schemas, and the checks that hold both writers and AI agents to a target instead of an adjective. I work upstream of interface copy, stay with the work through launch, and turn the decisions worth repeating into systems people and agents can use.",
  experience: [
    {
      when: "Nov 2022 - May 2026", org: "Meta", role: "Content designer → Senior content designer · Horizon, experimentation, and AI",
      bullets: [
        "Created Meta's content-standards infrastructure. Built Verso, the company's first domain-specific content-design agent, and the platform behind it: a deterministic lint toolkit, an 11-dimension measurement engine with per-product voice baselines computed from shipped strings, and a structured index of terminology rules, review blockers, and measurement profiles covering Instagram, Facebook, Messenger, WhatsApp, Quest, and Horizon.",
        "Led travel terminology across Meta Horizon OS: one vocabulary for calling, sessions, and travel across VR, mobile, and desktop surfaces. Also led the naming audit for the Meta Quest-to-Horizon OS rebrand.",
        "Established Meta Horizon's first content experimentation practice and led content designers across its major product areas, representing the organization. Built workshops and working tools for writing hypotheses and tracking tests.",
        "Brought content designers into agentic workflows through workshops and office hours. Taught local agent setup in VS Code, then helped designers author reusable skill files and deterministic scripts for the rules prose guidance could never reliably enforce.",
        "Helped turn the Meta Horizon phone app from a headset utility into a repeat-use mobile product. Led content from the early journeys and a strategy one-pager written for Mark Zuckerberg through the launch experiments; the feed experiment lifted 28-day retention by about 15%, and the quests homepage grew daily active use by nearly 5% in its first test.",
        "Defined the strategy and jobs to be done for Horizon Portals, including the metadata and progressive-disclosure framework for moving between virtual worlds. The work earned VP alignment and appeared in the Meta Connect 2024 keynote.",
        "Replaced billboard-style instruction with just-in-time spatial education: controllers and spatial cues teaching one thing at the moment it became relevant. Improved onboarding completion by nearly 30%, weekly active use by about 20%, and new-user retention by roughly 7%. The strategy and components were adopted by the Meta Quest onboarding team.",
      ],
    },
    {
      when: "Oct 2021 - Oct 2022", org: "Digbi Health", role: "Lead UX writer",
      bullets: [
        "Led end-to-end product content for a precision-health startup, translating microbiome, genetic, and clinical data into personalized journeys from onboarding through behavior change.",
      ],
    },
    {
      when: "Apr 2020 - Oct 2021", org: "8x8", role: "UX writer",
      bullets: [
        "Made enterprise voice, video, chat, contact-center, and phone-administration tools understandable to the business owners who had to configure them.",
      ],
    },
    {
      when: "Jul 2015 - Jun 2020", org: "WVU, VCU, and Army Logistics University", role: "Professor",
      bullets: [
        "Spent five years teaching composition and poetry at WVU and VCU, then training Army officers to turn complex, high-stakes information into clear, direct language.",
      ],
    },
  ],
  education: [
    { org: "Virginia Commonwealth University", role: "MFA, Poetry", when: "2018" },
    { org: "West Virginia University", role: "BA, English", when: "2014" },
  ],
  tools: ["Product strategy", "Interaction language", "Onboarding and education", "Experiment design", "Content modeling", "Terminology and taxonomy", "AI workflows and evals", "Workshop facilitation", "Figma", "Python"],
  publicWork: [
    {
      title: "Working papers",
      body: "A running list of short public studies on measuring and governing product language. calebstacy.com/papers",
    },
    {
      title: "slop-no-more",
      body: "A deterministic scanner for the rhetorical moves that make prose read as machine-written: a 26-family catalog, severity tiers and repair rules.",
    },
  ],
};
