/* Generated by tools/build-static.js — compiled ahead of time, do not edit. */

/* ---- plays/papers/two-brands (inline script) ---- */
(function () {
const {
  Report,
  ReportSection,
  DocFigure,
  NoteRef,
  Endnotes,
  References,
  Finding,
  DataTable,
  Ledger,
  FingerprintBars,
  PullQuote
} = window.CalebStacyPortfolioDesignSystem_4a3883;

/* ---------- formatting and labels only — every number below is read from results.json at
   runtime; nothing here is a measurement ---------- */

const DIM_LABEL = {
  involvement: "Involvement",
  information_density: "Information density",
  readability: "Readability",
  emotional_tone: "Emotional tone",
  lexical_sophistication: "Lexical sophistication",
  lexical_diversity: "Lexical diversity",
  concreteness: "Concreteness",
  syntactic_complexity: "Syntactic complexity",
  directness: "Directness",
  cadence: "Cadence",
  epistemic_stance: "Epistemic stance",
  specificity: "Specificity"
};
const DIM_ORDER = Object.keys(DIM_LABEL);
const SURFACE_LABEL = {
  help: "Netflix Help Center",
  tudum: "Tudum",
  marketing: "Netflix marketing",
  culture: "Netflix culture/jobs",
  support: "Discord Support",
  blog: "Discord Blog",
  company: "Discord company"
};
const TYPE_LABEL = {
  ui_string: "UI strings",
  heading: "Headings",
  procedural: "Procedural steps",
  body_prose: "Body prose"
};
const TYPE_ORDER = ["heading", "ui_string", "body_prose", "procedural"];
const MONTHS = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
function fmtDate(iso) {
  if (!iso) return "";
  const [y, m, d] = iso.split("-").map(Number);
  return d + " " + MONTHS[m - 1] + " " + y;
}
const fmt = n => n === null || n === undefined ? "—" : Number(n).toFixed(2);
const fmtP = p => {
  if (p === null || p === undefined) return "—";
  if (p < 0.001) return "<0.001";
  return Number(p).toFixed(3);
};
const fmtD = d => d === null || d === undefined ? "—" : (d > 0 ? "+" : "") + Number(d).toFixed(2);
const isEvaluated = r => r.status === "tested" || r.status === "degenerate_no_variance";
const hi = (value, on) => on ? {
  value,
  highlight: true
} : value;
function VerdictText({
  v
}) {
  const on = v === "separates";
  return /*#__PURE__*/React.createElement("span", {
    className: "tb-badge " + (on ? "tb-accent" : "tb-muted")
  }, v.replace(/_/g, " "));
}
function getCell(results, brand, surface, type) {
  return results.cells[brand + "." + surface + "." + type];
}
function fingerprintDims(results, brand, surface, type) {
  const cell = getCell(results, brand, surface, type);
  if (!cell) return [];
  return DIM_ORDER.map(dim => {
    const d = cell.dimensions[dim];
    if (!d || d.mean === null) return null;
    return {
      name: DIM_LABEL[dim],
      value: d.mean
    };
  }).filter(Boolean);
}

/* ---------- app ---------- */

function App() {
  const [results, setResults] = React.useState(null);
  const [error, setError] = React.useState(null);
  React.useEffect(() => {
    fetch("./results.json").then(r => {
      if (!r.ok) throw new Error("HTTP " + r.status);
      return r.json();
    }).then(setResults).catch(e => setError(e.message || String(e)));
  }, []);
  if (error) {
    return /*#__PURE__*/React.createElement("div", {
      className: "errbox"
    }, "Could not load ", /*#__PURE__*/React.createElement("code", null, "results.json"), " (", error, "). Every number on this page is read from that file at runtime. Open this page over a local server, not as a bare file.");
  }
  if (!results) {
    return /*#__PURE__*/React.createElement("div", {
      className: "errbox"
    }, "Loading results.json…");
  }
  const st = results.statistics;
  const pct = st.n_tested > 0 ? Math.round(st.n_separates / st.n_tested * 100) : 0;
  const totalPages = Object.values(results.corpus_manifest).reduce((a, m) => a + m.pages_fetched_ok, 0);
  const separatingRows = st.rows.filter(r => r.verdict === "separates").slice().sort((a, b) => Math.abs(b.cohens_d) - Math.abs(a.cohens_d));
  const smallN = separatingRows.filter(r => Math.min(r.netflix_n, r.discord_n) < 10);
  const topRow = separatingRows.find(r => r.type === "heading" && r.dimension === "directness") || separatingRows[0];
  const separatingTableRows = separatingRows.map(r => [TYPE_LABEL[r.type], DIM_LABEL[r.dimension], r.netflix_surface + " / " + r.discord_surface, fmt(r.netflix_mean) + " (n=" + r.netflix_n + ")", fmt(r.discord_mean) + " (n=" + r.discord_n + ")", fmtD(r.cohens_d), fmtP(r.p_adj_bh), hi(String(Math.min(r.netflix_n, r.discord_n)), Math.min(r.netflix_n, r.discord_n) < 10)]);
  const chunk = (arr, n) => {
    const out = [];
    for (let i = 0; i < arr.length; i += n) out.push(arr.slice(i, i + n));
    return out;
  };
  const separatingChunks = chunk(separatingTableRows, 11);
  const outcomeByType = TYPE_ORDER.map(t => {
    const rows = st.rows.filter(r => r.type === t);
    return [TYPE_LABEL[t], String(rows.length), String(rows.filter(r => r.verdict === "separates").length), String(rows.filter(r => r.verdict === "underpowered").length), String(rows.filter(r => r.verdict === "no_meaningful_difference").length), String(rows.filter(r => r.verdict === "insufficient_data").length)];
  });
  const depthSummary = [["netflix", ["help", "tudum", "marketing", "culture"]], ["discord", ["support", "blog", "marketing", "company"]]].flatMap(([brand, surfaces]) => surfaces.map(surface => {
    let total = 0,
      met = 0;
    TYPE_ORDER.forEach(t => {
      const a = results.achieved_n[brand + "." + surface + "." + t];
      if (a) {
        total += a.n_items_scored;
        if (a.target_met) met++;
      }
    });
    const label = brand === "netflix" ? SURFACE_LABEL[surface] : surface === "marketing" ? "Discord marketing" : SURFACE_LABEL[surface];
    return [label, String(total), met + " of 4"];
  }));
  return /*#__PURE__*/React.createElement(Report, {
    title: "Netflix and Discord, measured",
    runningHead: "Netflix and Discord, measured — working paper",
    status: "Working paper",
    author: "Caleb Stacy",
    date: fmtDate(results.generated),
    plain: /*#__PURE__*/React.createElement("p", {
      style: {
        margin: 0
      }
    }, "Two companies' everyday writing (help pages, blog posts, marketing copy, careers pages) was run through the same reading instrument and split apart by what kind of text it is, because a button label reads nothing like a paragraph on any site. Where there was enough text collected to trust the result, Netflix and Discord genuinely do write differently about one comparison in six, and this paper says exactly where. Most of the other five in six are not \"no difference.\" Most of them are \"not enough text was collected to know,\" which this paper reports as plainly as the differences it did find. This is a redo of an earlier attempt that used the wrong statistical test on too little text; both are fixed here."),
    subtitle: "A corrected voice measurement across eight public pages, four per company, with a real significance test, a correction for running many tests at once, and a stated detection floor for every comparison.",
    abstract: /*#__PURE__*/React.createElement("p", {
      style: {
        margin: 0
      }
    }, "Eight public surfaces, four per company, run through the same twelve-dimension psycholinguistic engine, segmented by the kind of string each one is rather than by page. A button label, a heading, a paragraph, and a numbered step are pooled and tested separately. ", results.statistics.n_comparisons_attempted, " comparisons were attempted; ", results.statistics.n_tested, " had enough text on both sides to test at all. This is a reading, not a review; nowhere below does the word \"should\" appear about either company.")
  }, /*#__PURE__*/React.createElement(ReportSection, {
    id: "headline",
    title: "What this measured, and what it found"
  }, /*#__PURE__*/React.createElement(Finding, {
    measured: st.n_separates + "/" + st.n_tested + " separate (BH-adj p<.05, |d|≥0.5) · " + st.n_underpowered + " underpowered · " + st.n_comparisons_attempted + " attempted",
    verdict: "read plainly"
  }, "Where there was enough text collected to trust the result, Netflix and Discord's writing really is different about one comparison in six. More than half of everything tested (over three times as many comparisons as came back \"different\") simply didn't have enough text behind it to say anything reliable either way. That's most of the honest story here: how much couldn't be checked at all matters as much as what came out different."), /*#__PURE__*/React.createElement("p", {
    style: {
      margin: "0 0 1em"
    }
  }, "A comparison here is one measured quality of writing (how readable it is, how directly it speaks to the reader, and ten others) on one kind of string (a heading, a button label, a paragraph, a numbered step), read on one matched pair of pages: Netflix's help center against Discord's support pages, Tudum against Discord's blog, and the same pairing again for marketing and careers pages. ", totalPages, " pages were fetched across both companies to build the text collection this runs on."), /*#__PURE__*/React.createElement(DocFigure, {
    caption: "Every comparison this run attempted, and how each one resolved.",
    source: "results.json · statistics"
  }, /*#__PURE__*/React.createElement(Ledger, {
    label: "This run's full family of tests",
    items: [{
      value: String(st.n_comparisons_attempted),
      label: "comparisons attempted"
    }, {
      value: String(st.n_tested),
      label: "had enough text on both sides to test"
    }, {
      value: String(st.n_separates),
      label: "separate, with a real-sized, trustworthy gap"
    }, {
      value: String(st.n_underpowered),
      label: "too little text to trust a “no difference” reading"
    }, {
      value: String(st.n_no_meaningful_difference),
      label: "enough text, and genuinely no difference found"
    }, {
      value: String(st.n_insufficient_data),
      label: "too little text on one side to test at all"
    }]
  }))), /*#__PURE__*/React.createElement(ReportSection, {
    id: "changed",
    title: "What changed since the first attempt"
  }, /*#__PURE__*/React.createElement(Finding, {
    verdict: "corrected"
  }, "The first attempt at this measurement called a difference \"real\" using a test built for checking how spread out individual samples are. That is not the right yardstick for comparing two averages, and it was too strict at the small sample sizes that attempt collected. This run fixes that with the correct significance test, corrects for the fact that many tests were run at once, collects roughly five times as much text per page type and rebuilds the text-collection pipeline after a manual read of the first attempt's own samples turned up real contamination: an editorial page mistagged as a how-to guide, a headline mistagged as UI text, a paragraph mistagged as a heading."), /*#__PURE__*/React.createElement("p", {
    style: {
      margin: 0
    }
  }, "Rerunning the correct test on the first attempt's own, smaller collection (no new text, just the right statistics) raised its reported separation rate from about 15% to about 22%. Both numbers describe the same old, thinner collection; this page's ", pct, "% describes a new, roughly five-times-deeper one, corrected on both counts at once.", /*#__PURE__*/React.createElement(NoteRef, null))), /*#__PURE__*/React.createElement(ReportSection, {
    id: "method",
    title: "How much text this is actually built on"
  }, /*#__PURE__*/React.createElement(Finding, {
    measured: totalPages + " pages fetched · " + st.n_comparisons_attempted + " comparisons attempted",
    verdict: "collection depth"
  }, "Every comparison below only means something if there was enough text behind it. Some pages simply don't have much of a given kind of writing to collect. A careers page has almost no numbered instructions, and a company only has so many real interface buttons to name, no matter how many pages get fetched. This paper reports that limit honestly rather than papering over it."), /*#__PURE__*/React.createElement(DocFigure, {
    kind: "table",
    wide: true,
    caption: "Text units actually scored per site and page type, and how many of the four writing kinds reached their collection target.",
    source: "results.json · achieved_n"
  }, /*#__PURE__*/React.createElement(DataTable, {
    variant: "meta",
    columns: ["Surface", "Scored units (all 4 types)", "Types that met target"],
    rows: depthSummary
  })), /*#__PURE__*/React.createElement("p", {
    style: {
      margin: 0,
      color: "var(--story-muted)"
    }
  }, "The shortfall is concentrated in exactly the two places you'd expect: marketing pages (the smallest surfaces by real page count on both sites) and numbered instructions outside the two help-centre-shaped surfaces (most page types simply don't contain many, if any).")), /*#__PURE__*/React.createElement(ReportSection, {
    id: "stats",
    title: "The statistics, in plain terms"
  }, /*#__PURE__*/React.createElement(Finding, {
    measured: "α=0.05 · power=0.80 · called “separates” only at |d|≥0.5 and BH-adjusted p<.05",
    verdict: "method"
  }, "Four numbers were computed for every comparison, not one: whether the gap is bigger than you'd expect from random noise, how big the gap actually is, whether it survives the fact that roughly 190 tests were run at once (some will look \"significant\" by chance alone), and how big a gap this specific amount of collected text could even have found. A comparison only counts as \"the two companies differ\" if it clears the first three. It counts as \"too little text to trust\" if the fourth number says the collected sample couldn't have reliably found even a real, medium-sized difference. A null result there is reported as uninformative, not folded in as \"no difference.\""), /*#__PURE__*/React.createElement("p", {
    style: {
      margin: 0
    }
  }, "The standard formula for \"enough text to reliably find a real difference\" calls for roughly 63 examples on each side; this run's own collection target of 40 (100+ for headings and button labels) sits below that on purpose, and the gap between the two is exactly why so many comparisons above land as \"too little text\" rather than a clean yes or no.")), /*#__PURE__*/React.createElement(ReportSection, {
    id: "differ",
    title: "Where the two companies differ most clearly"
  }, /*#__PURE__*/React.createElement(Finding, {
    measured: topRow ? DIM_LABEL[topRow.dimension] + " · " + TYPE_LABEL[topRow.type] + " · " + topRow.netflix_surface + "/" + topRow.discord_surface + " · d=" + fmtD(topRow.cohens_d) + " · n=" + topRow.netflix_n + "/" + topRow.discord_n : "—",
    verdict: "separates"
  }, "The clearest, best-supported gap in the whole comparison shows up in the weekly entertainment headlines: Discord's blog headlines read like a plain statement of fact, and Tudum's read like an invitation, a soft, come-hither phrasing. The gap is both large and measured on well over a hundred headlines on each side, not a handful."), topRow && /*#__PURE__*/React.createElement(DocFigure, {
    caption: "Headline writing on " + SURFACE_LABEL[topRow.netflix_surface] + " and " + SURFACE_LABEL[topRow.discord_surface] + ", all twelve measured qualities.",
    source: "results.json · cells." + "netflix." + topRow.netflix_surface + ".heading, discord." + topRow.discord_surface + ".heading"
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      display: "grid",
      gridTemplateColumns: "1fr 1fr",
      gap: "clamp(16px,3vw,32px)"
    }
  }, /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement("p", {
    style: {
      margin: "0 0 8px",
      fontFamily: "var(--font-mono)",
      fontSize: 9,
      fontWeight: 700,
      color: "var(--story-muted)"
    }
  }, SURFACE_LABEL[topRow.netflix_surface]), /*#__PURE__*/React.createElement(FingerprintBars, {
    dimensions: fingerprintDims(results, "netflix", topRow.netflix_surface, topRow.type),
    scale: 10,
    showBand: false
  })), /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement("p", {
    style: {
      margin: "0 0 8px",
      fontFamily: "var(--font-mono)",
      fontSize: 9,
      fontWeight: 700,
      color: "var(--story-muted)"
    }
  }, SURFACE_LABEL[topRow.discord_surface]), /*#__PURE__*/React.createElement(FingerprintBars, {
    dimensions: fingerprintDims(results, "discord", topRow.discord_surface, topRow.type),
    scale: 10,
    showBand: false
  })))), /*#__PURE__*/React.createElement("p", {
    style: {
      margin: "0 0 1em"
    }
  }, "Below is the complete list of every comparison that separated under the correction: ", separatingRows.length, " of them, all of them, not a curated top few. ", smallN.length > 0 && /*#__PURE__*/React.createElement(React.Fragment, null, smallN.length, " of the ", separatingRows.length, " sit on a sample as small as ", Math.min(...smallN.map(r => Math.min(r.netflix_n, r.discord_n))), " items on one side. That's technically over the line, but too thin to lean on, and marked below rather than left to blend in.", /*#__PURE__*/React.createElement(NoteRef, null))), separatingChunks.map((rows, i) => /*#__PURE__*/React.createElement(DocFigure, {
    key: i,
    kind: "table",
    wide: true,
    caption: "Every comparison that separates under the correction, largest gap first. The complete list spans " + separatingChunks.length + " parts (" + (i + 1) + " of " + separatingChunks.length + "), smallest sample size on either side flagged.",
    source: "results.json · statistics.rows, filtered to verdict=separates"
  }, /*#__PURE__*/React.createElement(DataTable, {
    variant: "meta",
    columns: ["Type", "Dimension", "Pair", "Netflix", "Discord", "d", "p (BH-adj)", "Smaller n"],
    rows: rows
  })))), /*#__PURE__*/React.createElement(ReportSection, {
    id: "everything-else",
    title: "Everything else, by the numbers"
  }, /*#__PURE__*/React.createElement(Finding, {
    verdict: "read plainly"
  }, "Most of what was tested came back one of two ways: genuinely no difference between the two companies, or too little text collected to say anything reliable at all. This breaks that split out by the four kinds of writing, because the split isn't even. Headings had the deepest collection and the most conclusive answers either way; numbered instructions and button labels had the thinnest and the most \"couldn't tell.\""), /*#__PURE__*/React.createElement(DocFigure, {
    kind: "table",
    wide: true,
    caption: "Every tested comparison, grouped by page-content type and outcome.",
    source: "results.json · statistics.rows, grouped by type"
  }, /*#__PURE__*/React.createElement(DataTable, {
    variant: "meta",
    columns: ["Type", "Attempted", "Separates", "Too little text", "No real difference", "Couldn't test at all"],
    rows: outcomeByType
  }))), /*#__PURE__*/React.createElement(ReportSection, {
    id: "verdict",
    title: pct + "% of trustworthy comparisons separate the two companies"
  }, /*#__PURE__*/React.createElement(Finding, {
    verdict: "descriptive"
  }, "Nothing on this page is a recommendation. Two companies, or two different pages on the same site, having different voices is the expected and correct outcome of measuring writing rather than judging it. Where a quality doesn't separate the two companies, that's reported as a real finding about the two surfaces' actual writing, and about how much this instrument can resolve at this sample size. It is not a gap in the data."), /*#__PURE__*/React.createElement("p", {
    style: {
      margin: 0
    }
  }, st.n_separates, " of ", st.n_tested, " adequately-tested comparisons show a corrected, real-sized gap between matched Netflix and Discord pages. ", st.n_underpowered, " more could not have reliably found a real difference at the amount of text actually collected, even where the raw numbers looked different. Those are reported as too little text to trust, not folded into either a positive or negative finding. ", st.n_no_meaningful_difference, " had enough text and found nothing: a real result, not a hole in the collection.")), /*#__PURE__*/React.createElement(Endnotes, {
    notes: ["Both the 15% and 22% figures describe the same first-attempt collection (median 7–8 examples per comparison, and as few as 3–4 for headings), re-scored with the correct test rather than re-collected. This run's own collection is roughly five times deeper per cell.", "Two of the 22 separating comparisons above sit on a sample as small as three items on one side (a numbered-instructions comparison on Tudum). The correction still technically clears them, but a sample that thin is not something this page asks a reader to lean on. It is flagged in the table rather than quietly included.", "Two dimensions in this engine are known approximations rather than published norms: emotional tone runs on an in-house word list rather than the Warriner valence/arousal/dominance norms, and concreteness is a suffix-counting proxy rather than the Brysbaert concreteness norms. Every score is comparative within this run, not an absolute external scale."]
  }), /*#__PURE__*/React.createElement(References, {
    items: [{
      text: "Welch, B. L. (1947). The generalization of ‘Student's’ problem when several different population variances are involved. Biometrika, 34(1–2), 28–35."
    }, {
      text: "Cohen, J. (1988). Statistical Power Analysis for the Behavioral Sciences (2nd ed.). Lawrence Erlbaum Associates."
    }, {
      text: "Benjamini, Y., & Hochberg, Y. (1995). Controlling the false discovery rate: A practical and powerful approach to multiple testing. Journal of the Royal Statistical Society: Series B, 57(1), 289–300."
    }, {
      text: "Flesch, R. (1948). A new readability yardstick. Journal of Applied Psychology, 32(3), 221–233."
    }, {
      text: "Warriner, A. B., Kuperman, V., & Brysbaert, M. (2013). Norms of valence, arousal, and dominance for 13,915 English lemmas. Behavior Research Methods, 45, 1191–1207."
    }, {
      text: "spaCy: industrial-strength natural language processing in Python.",
      href: "https://spacy.io"
    }]
  }));
}
ReactDOM.createRoot(document.getElementById("root")).render(/*#__PURE__*/React.createElement(App, null));
})();
