/* Generated by tools/build-static.js — compiled ahead of time, do not edit. */

/* ---- plays/netflix (inline script) ---- */
(function () {
const {
  Report,
  ReportSection,
  DocFigure,
  NoteRef,
  Endnotes,
  References,
  Finding,
  DataTable,
  Ledger,
  FingerprintBars,
  PullQuote,
  IndexRows,
  ProvenanceNote,
  Toolchain,
  Pipeline,
  ResearchGrid,
  CardGrid,
  GridCard
} = window.CalebStacyPortfolioDesignSystem_4a3883;

/* ---------- formatting and labels only — every number below is read from floor.json /
   terms.json / shelves.json at runtime; nothing here is a measurement ---------- */

const DIM_LABEL = {
  involvement: "Involvement",
  information_density: "Information density",
  readability: "Readability",
  emotional_tone: "Emotional tone",
  lexical_sophistication: "Lexical sophistication",
  lexical_diversity: "Lexical diversity",
  concreteness: "Concreteness",
  syntactic_complexity: "Syntactic complexity",
  directness: "Directness",
  cadence: "Cadence",
  epistemic_stance: "Epistemic stance",
  specificity: "Specificity"
};
const DIM_ORDER = Object.keys(DIM_LABEL);
const SURFACE_LABEL = {
  help: "Help Center",
  tudum: "Tudum",
  marketing: "Marketing",
  culture: "Culture/jobs"
};
const TYPE_LABEL = {
  heading: "Headings",
  procedural: "Procedural steps",
  body_prose: "Body prose",
  ui_string: "UI strings"
};
const TYPE_ORDER = ["heading", "procedural", "body_prose", "ui_string"];
const KIND_LABEL = {
  synonym_competition: "Synonym competition",
  form_variation: "Form variation",
  surface_exclusive: "Surface-exclusive"
};
const MONTHS = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
function fmtDate(iso) {
  if (!iso) return "";
  const [y, m, d] = iso.split("-").map(Number);
  return d + " " + MONTHS[m - 1] + " " + y;
}
const fmt = n => n === null || n === undefined ? "—" : Number(n).toFixed(2);
const fmtN = n => Number(n).toLocaleString("en-US");
const fmtP = p => {
  if (p === null || p === undefined) return "—";
  if (p < 0.001) return "<0.001";
  return Number(p).toFixed(3);
};
const fmtD = d => d === null || d === undefined ? "—" : (d > 0 ? "+" : "") + Number(d).toFixed(2);
const hi = (value, on) => on ? {
  value,
  highlight: true
} : value;
const cnt = (bySurface, key) => bySurface[key] ? String(bySurface[key]) : "—";
function VerdictText({
  v
}) {
  const on = v === "extends";
  return /*#__PURE__*/React.createElement("span", {
    className: "nf-badge " + (on ? "nf-accent" : "nf-muted")
  }, v.replace(/_/g, " "));
}

/* ---------- app ---------- */

function App() {
  const [data, setData] = React.useState(null);
  const [error, setError] = React.useState(null);
  React.useEffect(() => {
    Promise.all([fetch("./floor.json").then(r => {
      if (!r.ok) throw new Error("floor.json HTTP " + r.status);
      return r.json();
    }), fetch("./terms.json").then(r => {
      if (!r.ok) throw new Error("terms.json HTTP " + r.status);
      return r.json();
    }), fetch("../netflix-shelves/shelves.json").then(r => {
      if (!r.ok) throw new Error("shelves.json HTTP " + r.status);
      return r.json();
    })]).then(([floor, terms, shelves]) => setData({
      floor,
      terms,
      shelves
    })).catch(e => setError(e.message || String(e)));
  }, []);
  if (error) {
    return /*#__PURE__*/React.createElement("div", {
      className: "errbox"
    }, "Could not load the data files (", error, "). Every number on this page is read from ", /*#__PURE__*/React.createElement("code", null, "floor.json"), ", ", /*#__PURE__*/React.createElement("code", null, "terms.json"), ", and ", /*#__PURE__*/React.createElement("code", null, "shelves.json"), " at runtime. Open this page over a local server, not as a bare file.");
  }
  if (!data) {
    return /*#__PURE__*/React.createElement("div", {
      className: "errbox"
    }, "Loading…");
  }
  const {
    floor,
    terms,
    shelves
  } = data;
  const S = floor.summary;
  const productContentUnits = shelves.terminology.families;
  const extendsRows = floor.deviations.filter(d => d.verdict === "extends");
  const surfaceOrder = {
    help: 0,
    tudum: 1,
    culture: 2,
    marketing: 3
  };
  const extendsSorted = extendsRows.slice().sort((a, b) => {
    if (surfaceOrder[a.surface] !== surfaceOrder[b.surface]) return surfaceOrder[a.surface] - surfaceOrder[b.surface];
    return Math.abs(b.cohens_d) - Math.abs(a.cohens_d);
  });
  const extendsTableRows = extendsSorted.map(r => [SURFACE_LABEL[r.surface], DIM_LABEL[r.dimension], fmt(r.mean) + " (n=" + r.n + ")", fmt(r.floor_mean), fmtD(r.deviation), fmtD(r.cohens_d), fmtP(r.p_adj_bh)]);
  const byTypeRows = TYPE_ORDER.map(t => {
    const bt = S.by_string_type[t];
    return [TYPE_LABEL[t], bt.n_cells_with_floor + " of 12", String(bt.n_extends), String(bt.n_within_floor), String(bt.n_underpowered), String(bt.n_insufficient_data)];
  });
  const headingTested = floor.deviations.filter(d => d.string_type === "heading" && d.status === "tested");
  const headingMdes = headingTested.map(d => d.mde_d);
  const headingInvolvement = floor.deviations.filter(d => d.string_type === "heading" && d.dimension === "involvement" && (d.surface === "help" || d.surface === "tudum"));
  const proceduralHelp = floor.deviations.filter(d => d.string_type === "procedural" && d.surface === "help");
  const procHelpRows = DIM_ORDER.map(dim => {
    const row = proceduralHelp.find(d => d.dimension === dim);
    return [DIM_LABEL[dim], row ? fmt(row.mean) : "—"];
  });
  const marketingBody = floor.deviations.filter(d => d.string_type === "body_prose" && d.surface === "marketing");
  const marketingTested = marketingBody.filter(d => d.status === "tested");
  const marketingRows = marketingTested.map(row => [DIM_LABEL[row.dimension], fmt(row.mean) + " (n=" + row.n + ")", fmt(row.mde_d)]);
  const uiFloors = floor.floors.filter(f => f.string_type === "ui_string");
  const uiFloorsComputed = uiFloors.filter(f => f.floor_mean !== null).length;
  function bodyFingerprint(surface) {
    return DIM_ORDER.map(dim => {
      const row = floor.deviations.find(d => d.string_type === "body_prose" && d.surface === surface && d.dimension === dim);
      if (!row || row.mean == null) return null;
      return {
        name: DIM_LABEL[dim],
        value: row.mean
      };
    }).filter(Boolean);
  }
  const getCandidate = id => terms.top_candidates.find(c => c.id === id);
  const contentUnit = getCandidate("content-unit-pairing");
  const myList = getCandidate("save-for-later");
  const ctaCasing = getCandidate("cta-register-by-surface");
  const roleNaming = getCandidate("role-naming");
  const paidRel = getCandidate("paid-relationship");
  const cuRows = contentUnit.entries.map(e => [e.variant, cnt(e.counts_by_surface, "help"), cnt(e.counts_by_surface, "tudum"), cnt(e.counts_by_surface, "marketing"), cnt(e.counts_by_surface, "culture"), String(e.total)]);
  const myListRows = myList.entries.map(e => [e.variant, cnt(e.counts_by_surface, "help"), cnt(e.counts_by_surface, "tudum"), String(e.total)]);
  const ctaRows = ctaCasing.entries.map(e => {
    const surface = Object.keys(e.counts_by_surface)[0];
    return [e.quotes[0].quote, SURFACE_LABEL[surface], String(e.counts_by_surface[surface])];
  });
  const roleRows = roleNaming.entries.map(e => [e.variant, cnt(e.counts_by_surface, "help"), cnt(e.counts_by_surface, "tudum"), cnt(e.counts_by_surface, "culture"), String(e.total)]);
  const paidRows = paidRel.entries.map(e => [e.variant, cnt(e.counts_by_surface, "help"), cnt(e.counts_by_surface, "tudum"), cnt(e.counts_by_surface, "marketing"), String(e.total)]);
  const rankedRows = terms.top_candidates.slice().sort((a, b) => a.rank - b.rank).map(c => [String(c.rank), c.title, KIND_LABEL[c.kind] || c.kind, String(c.n_surfaces_touched), String(c.total_occurrences)]);
  const homonymRows = terms.flagged_homonym_collisions.map(c => [c.concept_key, c.collision]);
  const tudumDirectness = extendsRows.find(r => r.surface === "tudum" && r.dimension === "directness");
  const cultureReadability = extendsRows.find(r => r.surface === "culture" && r.dimension === "readability");
  const recordRows = [{
    id: "extension.body_prose.directness.tudum.v1",
    asserts: "Tudum's body prose reads measurably less direct than the shared Netflix floor (deviation " + fmtD(tudumDirectness.deviation) + ", Cohen's d " + fmtD(tudumDirectness.cohens_d) + ", BH-adjusted p" + fmtP(tudumDirectness.p_adj_bh) + ", n=" + tudumDirectness.n + " against " + tudumDirectness.rest_n + ", adequately powered at MDE " + fmt(tudumDirectness.mde_d) + ").",
    meta: ["kind: extension (demonstration)", "status: adopted-shaped", "owner: surface voice lead", "evidence: floor.json · tudum/body_prose/directness"]
  }, {
    id: "extension.body_prose.readability.culture.v1",
    asserts: "Culture's body prose reads measurably less readable than the shared Netflix floor (deviation " + fmtD(cultureReadability.deviation) + ", Cohen's d " + fmtD(cultureReadability.cohens_d) + ", BH-adjusted p" + fmtP(cultureReadability.p_adj_bh) + ", n=" + cultureReadability.n + " against " + cultureReadability.rest_n + "), the largest single gap in the whole run.",
    meta: ["kind: extension (demonstration)", "status: adopted-shaped", "owner: surface voice lead", "evidence: floor.json · culture/body_prose/readability"]
  }, {
    id: "vocabulary.content_unit.series_film_vs_tv_show_movie.v0",
    asserts: "Help and marketing pair “TV show” with “movie”; Tudum and culture pair “series” with “film,” for what reads like the same content-type concept — " + contentUnit.total_occurrences + " occurrences across all four surfaces. No public record says whether that split is a deliberate register or unmanaged drift.",
    meta: ["kind: vocabulary (proposed shape, undefined in the schema)", "status: proposed — no owner assigned", "evidence: terms.json · content-unit-pairing", "blocked on: a ruling, not more data"]
  }];
  return /*#__PURE__*/React.createElement(Report, {
    title: "Netflix's public voice, indexed",
    runningHead: "Netflix's public voice, indexed — the full index",
    status: "The full index",
    author: "Caleb Stacy",
    date: fmtDate(floor.run.date),
    plain: /*#__PURE__*/React.createElement("p", {
      style: {
        margin: 0
      }
    }, "Netflix's Help Center, Tudum, its marketing pages, and its careers pages are all publicly Netflix, and none of them read quite like the others. I ran all four surfaces through the same twelve-dimension reading on public pages fetched and scored on ", fmtDate(floor.run.date), ", and found ", S.n_extends, " adequately powered places where a surface genuinely departs from what the other three share. The method itself ships publicly as Word Math. Divergence like that is normal; every one of these surfaces is written for a different reader, and Netflix may well have ruled on every difference internally. Whether it has is the one thing this method can't see. What the public numbers do support is deriving the record such a ruling would live in — and the last section of this page does exactly that."),
    subtitle: "A shared voice floor and eleven measured departures from it, twenty-three places where the surfaces name the same thing differently, and the record shape that would settle which of it is intended.",
    abstract: /*#__PURE__*/React.createElement("p", {
      style: {
        margin: 0
      }
    }, "Every public page was split by what kind of string it carries before any two surfaces were compared — a heading reads nothing like a numbered step — and a floor was only computed where at least two of the four surfaces had enough sampled text to support one. Where a surface's own reading departs from that floor, the gap was tested, not eyeballed: a real effect size, a significance test corrected for running many comparisons at once, and a stated detection floor per comparison. A separate pass mined the same four surfaces for the words themselves, where two surfaces reach for different names for one concept, and ranked what it found by how many surfaces the pattern actually touches. Nothing below is advice to Netflix; every claim here is either a measured number or a stated absence of one.")
  }, /*#__PURE__*/React.createElement(ReportSection, {
    id: "headline",
    title: "What this page shows"
  }, /*#__PURE__*/React.createElement(Finding, {
    measured: S.n_cells + " cells measured · " + S.n_extends + " extend the floor · " + S.n_within_floor + " within it · " + S.n_underpowered + " underpowered · " + S.n_insufficient_data + " insufficient data",
    verdict: "read plainly"
  }, "Four Netflix surfaces, the same twelve-dimension reading applied to each, a shared floor computed wherever two or more surfaces had enough text to support one, and every surface's own departure from it tested rather than assumed. Separately: twenty-three places where the same concept gets a different name depending which surface is writing it. Whether any of it is intended can't be read from the outside — if a ruling exists, it isn't public. So the last section derives, from this page's own numbers, the records such a ruling would live in."), /*#__PURE__*/React.createElement(DocFigure, {
    caption: "Every reading this run attempted, and how each one resolved.",
    source: "floor.json · summary"
  }, /*#__PURE__*/React.createElement(Ledger, {
    label: "This run, at a glance",
    items: [{
      value: "4",
      label: "public Netflix surfaces measured"
    }, {
      value: "12",
      label: "voice dimensions read on each"
    }, {
      value: String(S.n_extends),
      label: "adequately powered departures from the shared floor"
    }, {
      value: "23",
      label: "ranked terminology-variation sets"
    }, {
      value: "3",
      label: "records derived from the run"
    }]
  }))), /*#__PURE__*/React.createElement(ReportSection, {
    id: "artifacts",
    title: "The files behind every number"
  }, /*#__PURE__*/React.createElement(Finding, {
    verdict: "infrastructure, not a chart of it"
  }, "Every figure and table on this page is read live from two JSON files sitting next to it, plus a third from a companion paper. They're linked here as what they are: files with a size and a record count, not footnotes at the bottom of a citation list."), /*#__PURE__*/React.createElement(DocFigure, {
    kind: "figure",
    caption: "The machine-readable record this page is built on.",
    source: "plays/netflix/"
  }, /*#__PURE__*/React.createElement(CardGrid, {
    label: "Source files",
    scope: "4 files",
    columns: 2
  }, /*#__PURE__*/React.createElement(GridCard, {
    label: "01",
    metric: "105 KB",
    title: /*#__PURE__*/React.createElement("a", {
      className: "nf-artifact-link",
      href: "./floor.json"
    }, "floor.json"),
    body: "48 measured (string type × dimension) cells, 192 per-surface readings, every t-test, effect size, and correction this page cites.",
    code: '"verdict": "extends"'
  }), /*#__PURE__*/React.createElement(GridCard, {
    label: "02",
    metric: "89 KB",
    title: /*#__PURE__*/React.createElement("a", {
      className: "nf-artifact-link",
      href: "./terms.json"
    }, "terms.json"),
    body: "23 ranked terminology sets, 190 quoted examples with their source URLs across 50 tracked term variants, plus 5 flagged homonym collisions kept out of the ranking.",
    code: '"quote": "My List"'
  }), /*#__PURE__*/React.createElement(GridCard, {
    label: "03",
    metric: "24 KB",
    title: /*#__PURE__*/React.createElement("a", {
      className: "nf-artifact-link",
      href: "../papers/governance/schema.json"
    }, "schema.json"),
    body: "The extension-model record shape a companion paper defines, instantiated below against this page's own numbers rather than described in the abstract.",
    code: '"kind": "extension"'
  }), /*#__PURE__*/React.createElement(GridCard, {
    label: "04",
    metric: "2 files",
    title: "derive_floor.py · mine_terms.py",
    body: "What produced floor.json and terms.json from the underlying page corpus, documented inline as method rather than left to infer from output.",
    code: 'python derive_floor.py'
  })))), /*#__PURE__*/React.createElement(ReportSection, {
    id: "floor",
    title: "The voice floor"
  }, /*#__PURE__*/React.createElement(Finding, {
    measured: S.n_cells_with_floor + " of " + S.n_cells + " cells have a computable floor · " + S.n_extends + " of " + S.n_tested_with_pvalue + " tested comparisons extend it",
    verdict: "method"
  }, "A floor only exists where at least two of the four surfaces have enough sampled text on that exact kind of writing and that exact dimension. A heading is never compared to a paragraph, and a three-item sample never anchors anything. ", S.n_cells_with_floor, " of ", S.n_cells, " (string type × dimension) cells clear that bar. All twelve that don't are the same string type: no Netflix surface's interface copy is long or varied enough, in enough separately-sampled batches, to be described by this method at all yet — see below."), /*#__PURE__*/React.createElement(DocFigure, {
    kind: "table",
    wide: true,
    caption: "Every cell this run attempted, grouped by what kind of string it is.",
    source: "floor.json · summary.by_string_type"
  }, /*#__PURE__*/React.createElement(DataTable, {
    variant: "meta",
    columns: ["Type", "Cells with a floor", "Extends", "Within floor", "Underpowered", "Insufficient data"],
    rows: byTypeRows
  })), /*#__PURE__*/React.createElement("p", {
    style: {
      margin: "1.2em 0 0.6em",
      fontWeight: 600
    }
  }, "Where a surface extends the floor"), /*#__PURE__*/React.createElement("p", {
    style: {
      margin: "0 0 1em"
    }
  }, "All ", S.n_extends, " adequately powered departures live in body prose, the one string type with enough per-item volume on every surface to test cleanly. Help, Tudum, and Culture each extend the floor on several dimensions. Marketing extends on none, not because its writing agrees with everyone else's but because there isn't enough of it to say either way (below)."), /*#__PURE__*/React.createElement(DocFigure, {
    kind: "table",
    wide: true,
    caption: "Every reading in this run that extends the shared floor, largest effect first within each surface.",
    source: "floor.json · deviations, filtered to verdict=extends"
  }, /*#__PURE__*/React.createElement(DataTable, {
    variant: "meta",
    columns: ["Surface", "Dimension", "Surface's own mean", "Shared floor", "Deviation", "Cohen's d", "BH-adj p"],
    rows: extendsTableRows
  })), /*#__PURE__*/React.createElement(DocFigure, {
    caption: "Body prose, Help Center against Tudum, all twelve measured dimensions. Directness moves in opposite directions on the same two surfaces: help extends toward more of it, Tudum toward less.",
    source: "floor.json · deviations, body_prose/help and body_prose/tudum"
  }, /*#__PURE__*/React.createElement("div", {
    "data-ds": "two-col",
    style: {
      display: "grid",
      gridTemplateColumns: "1fr 1fr",
      gap: "clamp(16px,3vw,32px)"
    }
  }, /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement("p", {
    style: {
      margin: "0 0 8px",
      fontFamily: "var(--font-mono)",
      fontSize: 9,
      fontWeight: 700,
      color: "var(--story-muted)"
    }
  }, "Help Center"), /*#__PURE__*/React.createElement(FingerprintBars, {
    dimensions: bodyFingerprint("help"),
    scale: 10,
    showBand: false
  })), /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement("p", {
    style: {
      margin: "0 0 8px",
      fontFamily: "var(--font-mono)",
      fontSize: 9,
      fontWeight: 700,
      color: "var(--story-muted)"
    }
  }, "Tudum"), /*#__PURE__*/React.createElement(FingerprintBars, {
    dimensions: bodyFingerprint("tudum"),
    scale: 10,
    showBand: false
  })))), /*#__PURE__*/React.createElement("p", {
    style: {
      margin: "1.2em 0 0.6em",
      fontWeight: 600
    }
  }, "Headings: a real gap the sample can't yet certify"), /*#__PURE__*/React.createElement("p", {
    style: {
      margin: "0 0 1em"
    }
  }, "Every one of the ", headingTested.length, " tested heading comparisons lands underpowered, at a minimum detectable effect between ", fmt(Math.min(...headingMdes)), " and ", fmt(Math.max(...headingMdes)), ", a hair over this run's own 0.5 bar for a trustworthy medium effect. That ceiling isn't scattered noise: Help Center's heading sample (n=", headingInvolvement.find(r => r.surface === "help")?.n, ") sets it, and Tudum's much larger sample barely moves the formula regardless of which of the twelve dimensions is tested. Involvement is the clearest case sitting just behind that line. Help Center headings read markedly less involved than Tudum's (", fmt(headingInvolvement.find(r => r.surface === "help")?.mean), " against ", fmt(headingInvolvement.find(r => r.surface === "tudum")?.mean), ", d=", fmtD(headingInvolvement.find(r => r.surface === "help")?.cohens_d), ", BH-adjusted p", fmtP(headingInvolvement.find(r => r.surface === "help")?.p_adj_bh), "). That's real and highly significant on the raw numbers, reported here as underpowered anyway, because the sample that produced it couldn't have reliably found a medium effect even if a smaller one were noise.", /*#__PURE__*/React.createElement(NoteRef, null)), /*#__PURE__*/React.createElement("p", {
    style: {
      margin: "1.2em 0 0.6em",
      fontWeight: 600
    }
  }, "Procedural steps: one surface, no floor to compare it against"), /*#__PURE__*/React.createElement("p", {
    style: {
      margin: "0 0 1em"
    }
  }, "Help Center is the only surface with enough numbered instructions to read at all (n=54 scored batches); Tudum, marketing, and culture never reach five. That leaves nothing to test Help Center's own procedural voice against, so its profile below is a real reading with nowhere to be a floor.", /*#__PURE__*/React.createElement(NoteRef, null)), /*#__PURE__*/React.createElement(DocFigure, {
    kind: "table",
    caption: "Help Center's own procedural-copy profile: the only surface this string type could be scored on at all.",
    source: "floor.json · deviations, procedural/help"
  }, /*#__PURE__*/React.createElement(DataTable, {
    variant: "meta",
    columns: ["Dimension", "Help Center's own mean (n=54)"],
    rows: procHelpRows
  })), /*#__PURE__*/React.createElement("p", {
    style: {
      margin: "1.2em 0 0.6em",
      fontWeight: 600
    }
  }, "Marketing: thin everywhere, and honest about it"), /*#__PURE__*/React.createElement("p", {
    style: {
      margin: "0 0 1em"
    }
  }, "Marketing's body prose reaches the sample floor on ", marketingTested.length, " of twelve dimensions, since its short paragraphs clear the word-count bar less often than the other three surfaces' longer ones, and every one of those ", marketingTested.length, " still lands underpowered against this run's own detection bar. Marketing extends nothing not because it agrees with the rest of Netflix, but because there was never enough of it collected to say either way. That's reported as a limit on the sample, not folded in as a quiet \"no difference.\""), /*#__PURE__*/React.createElement(DocFigure, {
    kind: "table",
    wide: true,
    caption: "Every marketing body-prose reading that reached the sample floor at all.",
    source: "floor.json · deviations, body_prose/marketing, status=tested"
  }, /*#__PURE__*/React.createElement(DataTable, {
    variant: "meta",
    columns: ["Dimension", "Marketing's own mean", "MDE (d)"],
    rows: marketingRows
  })), /*#__PURE__*/React.createElement("p", {
    style: {
      margin: "1.2em 0 0.6em",
      fontWeight: 600
    }
  }, "UI strings: the method declines to speak"), /*#__PURE__*/React.createElement("p", {
    style: {
      margin: "0 0 1.2em"
    }
  }, "None of the twelve UI-string cells compute a floor at all: ", uiFloorsComputed, " of 12. No Netflix surface's button labels, links, or short interface copy ever reach five scored items on any dimension; Help Center tops out around four. That's not a null finding presented as one. It's the method refusing to describe something it doesn't have enough of, which is the honest outcome, not a gap in the page."), /*#__PURE__*/React.createElement(ProvenanceNote, {
    label: "Known limits"
  }, "Two of the twelve dimensions are documented approximations rather than published norms: emotional tone runs on an in-house valence lexicon rather than the Warriner valence/arousal/dominance norms, and concreteness is a morphological suffix proxy rather than the Brysbaert concreteness norms. Every score above is comparative within this run, not an absolute external scale.")), /*#__PURE__*/React.createElement(ReportSection, {
    id: "terms",
    title: "Where the words themselves compete"
  }, /*#__PURE__*/React.createElement(Finding, {
    measured: terms.top_candidates.length + " ranked sets · " + terms.flagged_homonym_collisions.length + " homonym collisions caught and kept out",
    verdict: "mined, not assumed"
  }, "A separate pass read the same four surfaces for their actual vocabulary — noun phrases, named entities, and the imperative button labels a noun-chunk parser misses on its own — and grouped what it found into families that plausibly name one real-world concept. Every count and quote below is read live from that same pass; nothing here was re-typed or paraphrased into a cleaner story."), /*#__PURE__*/React.createElement("p", {
    style: {
      margin: "1.2em 0 0.6em",
      fontWeight: 600
    }
  }, "Content units: two disjoint working vocabularies"), /*#__PURE__*/React.createElement("p", {
    style: {
      margin: "0 0 1em"
    }
  }, "Help and marketing consistently pair \"TV show\" with \"movie.\" Tudum and culture instead reach for \"series\" and \"film,\" at far higher volume. Both pairs describe the same thing, scripted long-form video Netflix carries, but the two surface groups barely share a word for it: ", contentUnit.total_occurrences, " occurrences across all four surfaces, and no public record that says whether the split is a deliberate register or unmanaged drift."), /*#__PURE__*/React.createElement("p", {
    style: {
      margin: "0 0 1em"
    }
  }, "Netflix's public product taxonomy uses the movie/show family ", fmtN(productContentUnits.movie_show), " times against ", fmtN(productContentUnits.series_film), " uses of series/film. ", /*#__PURE__*/React.createElement("a", {
    href: "../netflix-shelves/index.html"
  }, "The companion paper"), " shows the naming grammar and the login boundary the crawl did not cross."), /*#__PURE__*/React.createElement(DocFigure, {
    kind: "table",
    wide: true,
    caption: "The content-unit family, every variant and where it's actually used.",
    source: "terms.json · content-unit-pairing"
  }, /*#__PURE__*/React.createElement(DataTable, {
    variant: "meta",
    columns: ["Term", "Help", "Tudum", "Marketing", "Culture", "Total"],
    rows: cuRows
  })), /*#__PURE__*/React.createElement("div", {
    style: {
      overflowX: "auto",
      margin: "1.2em 0"
    }
  }, /*#__PURE__*/React.createElement("div", {
    "data-ds": "two-col",
    style: {
      display: "grid",
      gridTemplateColumns: "1fr 1fr",
      gap: "clamp(16px,3vw,32px)"
    }
  }, /*#__PURE__*/React.createElement(PullQuote, {
    attribution: "Help Center, help.netflix.com/en/node/100163"
  }, "If you watch a TV show or movie that was produced in another region, you may not be able to turn off subtitles."), /*#__PURE__*/React.createElement(PullQuote, {
    attribution: "Tudum, netflix.com/tudum/articles/a-house-of-dynamite-kathryn-bigelow-release-date-cast-news"
  }, "Yes, check out the trailer, which offers our first glimpse at Elba’s role in the movie, below."))), /*#__PURE__*/React.createElement("p", {
    style: {
      margin: "1.2em 0 0.6em",
      fontWeight: 600
    }
  }, "\"My List\": the control that holds"), /*#__PURE__*/React.createElement("p", {
    style: {
      margin: "0 0 1em"
    }
  }, "Not every term drifts. \"My List\" is Netflix's actual save-for-later feature name, and it appears letter-identical, same two words, same capitalization, in Help Center's instructions and in Tudum's own on-page widget chrome, ", myList.entries[0].total, " times combined. Tudum's editorial writers occasionally reach for the generic \"watchlist\" instead, five times, in running prose recommending titles rather than naming the feature. Small n on the drift side, but a clean instance of a branded term holding everywhere it's a UI label and leaking only where it's being written about rather than pointed at."), /*#__PURE__*/React.createElement(DocFigure, {
    kind: "table",
    caption: "The governed term against its one generic synonym.",
    source: "terms.json · save-for-later"
  }, /*#__PURE__*/React.createElement(DataTable, {
    variant: "meta",
    columns: ["Term", "Help", "Tudum", "Total"],
    rows: myListRows
  })), /*#__PURE__*/React.createElement("p", {
    style: {
      margin: "1.2em 0 0.6em",
      fontWeight: 600
    }
  }, "A casing register nobody wrote down"), /*#__PURE__*/React.createElement("p", {
    style: {
      margin: "0 0 1em"
    }
  }, "Culture's calls to action shout: ALL CAPS, systematically. Help and Tudum's don't; Title Case, systematically. That's a real, consistent pattern across ", ctaCasing.total_occurrences, " occurrences, and it reads like a rule. It isn't written anywhere a machine, or a new writer joining culture's team, could check it against."), /*#__PURE__*/React.createElement(DocFigure, {
    kind: "table",
    caption: "Four call-to-action phrases, verbatim, and the surface each belongs to.",
    source: "terms.json · cta-register-by-surface"
  }, /*#__PURE__*/React.createElement(DataTable, {
    variant: "meta",
    columns: ["Phrase, verbatim", "Surface", "Count"],
    rows: ctaRows
  })), /*#__PURE__*/React.createElement("p", {
    style: {
      margin: "1.2em 0 0.6em",
      fontWeight: 600
    }
  }, "Who's watching: six words for one relationship"), /*#__PURE__*/React.createElement("p", {
    style: {
      margin: "0 0 1em"
    }
  }, "\"Member\" is the term that actually survives across three surfaces. Tudum's own editorial voice almost never uses it: ", roleNaming.entries.find(e => e.variant === "viewer").total, " uses of \"viewer\" and zero of \"member\" in the sampled text. Tudum and culture both also reach for the collective, marketing-register \"audience\" and \"fan,\" which help and marketing never use for this role. Subscriber, customer, and user exist on every surface but rarely, occasional stand-ins rather than real competitors to member or viewer."), /*#__PURE__*/React.createElement(DocFigure, {
    kind: "table",
    wide: true,
    caption: "Every term this run found naming the person on the other end of the screen.",
    source: "terms.json · role-naming"
  }, /*#__PURE__*/React.createElement(DataTable, {
    variant: "meta",
    columns: ["Term", "Help", "Tudum", "Culture", "Total"],
    rows: roleRows
  })), /*#__PURE__*/React.createElement("p", {
    style: {
      margin: "1.2em 0 0.6em",
      fontWeight: 600
    }
  }, "The paid relationship, in Help Center alone"), /*#__PURE__*/React.createElement("p", {
    style: {
      margin: "0 0 1em"
    }
  }, "Help Center alone uses three different nouns for closely related parts of a Netflix subscription: \"account\" (the login/profile container, and by far the dominant term), \"membership\" (the ongoing relationship), and \"subscription\" (the billing arrangement), plus \"plan\" for the pricing tier, shared with marketing. None of this is necessarily wrong; account, membership, and subscription genuinely name different things. But nothing on record says that's the intended split rather than three writers reaching for whatever felt right that day."), /*#__PURE__*/React.createElement(DocFigure, {
    kind: "table",
    caption: "The paid-relationship family, Help Center's own three-way split plus the shared pricing term.",
    source: "terms.json · paid-relationship"
  }, /*#__PURE__*/React.createElement(DataTable, {
    variant: "meta",
    columns: ["Term", "Help", "Tudum", "Marketing", "Total"],
    rows: paidRows
  })), /*#__PURE__*/React.createElement(ProvenanceNote, {
    label: "Five collisions kept out"
  }, "Reading example quotes during this pass caught five cases a pure count would have silently treated as signal: \"cast\" (help's AirPlay feature vs. Tudum's ensemble-of-actors sense), \"ad\"/\"AD\" (advertising vs. a reality-show contestant's nickname on Tudum), \"plan\" (a pricing plan vs. Tudum's generic \"a plan/scheme\"), \"role\" (a job on culture vs. a dramatic role on Tudum), and \"category\"/\"collection\" (content-browse UI vs. awards-show categories vs. CCPA's \"categories of personal information\"). All five are excluded from the ranked sets above rather than presented as clean terminology signal."), /*#__PURE__*/React.createElement("p", {
    style: {
      margin: "1.2em 0 0.6em",
      fontWeight: 600
    }
  }, "The full ranked set"), /*#__PURE__*/React.createElement("p", {
    style: {
      margin: "0 0 1em"
    }
  }, "The five above are the strongest specimens, not the whole list. All ", terms.top_candidates.length, " ranked sets, by surfaces touched and total occurrences:"), /*#__PURE__*/React.createElement(DocFigure, {
    kind: "table",
    wide: true,
    caption: "Every terminology-variation set this run curated, ranked by surface spread then volume.",
    source: "terms.json · top_candidates"
  }, /*#__PURE__*/React.createElement(DataTable, {
    variant: "meta",
    columns: ["Rank", "Set", "Kind", "Surfaces touched", "Occurrences"],
    rows: rankedRows
  }))), /*#__PURE__*/React.createElement(ReportSection, {
    id: "record",
    title: "The record that would decide"
  }, /*#__PURE__*/React.createElement(Finding, {
    verdict: "the missing piece"
  }, "A shared floor and a measured departure from it don't, on their own, say whether the departure is allowed. That's a different question, and it needs a different kind of document: one that names the claim, the exact evidence behind it, who's allowed to change it, and what happens once someone finds a better number. A companion paper builds that record shape in full, on a different comparison. Below, the same shape is instantiated against this page's own numbers."), /*#__PURE__*/React.createElement("p", {
    style: {
      margin: "0 0 1em"
    }
  }, "A record here is either a ", /*#__PURE__*/React.createElement("strong", null, "floor"), " (the default, until something more specific overrides it) or an ", /*#__PURE__*/React.createElement("strong", null, "extension"), ", scoped to one surface. Where an adopted extension's scope covers a surface, it wins there; the floor keeps applying everywhere nothing more specific reaches. Nothing is ever deleted. A record's status moves to deprecated, and whatever cited its old id resolves forward rather than breaking. An adopted band is also an experimentable one: every dimension is an independent variable, so \"warmer support copy\" can run as a hypothesis with a readout instead of shipping as a preference with a sponsor."), /*#__PURE__*/React.createElement(DocFigure, {
    caption: "Three records, instantiated against this page's own findings rather than invented ones.",
    source: "Record shape: ../papers/governance/schema.json · record_shape. Evidence: floor.json, terms.json."
  }, /*#__PURE__*/React.createElement(IndexRows, {
    label: "Instantiated records",
    rows: recordRows
  })), /*#__PURE__*/React.createElement("p", {
    style: {
      margin: "0 0 1em"
    }
  }, "The third record uses a kind the schema doesn't define yet — ", /*#__PURE__*/React.createElement("code", null, "vocabulary"), " — because a named-term choice isn't a continuous reading a band-check can score; it's binary, and it needs its own shape. Proposing that shape is future work, not shown here. What the record above can already do is name the open question precisely enough for an owner to rule on it, which a page of counts by itself can't."), /*#__PURE__*/React.createElement(ProvenanceNote, {
    label: "What this section is not saying"
  }, "These are not real Netflix governance records, and nobody at Netflix asked for this schema. They're the extension-model mechanism, instantiated on real measured numbers from a public run, because a schema shown on invented numbers is a mockup, not a demonstration. ", /*#__PURE__*/React.createElement("code", null, "owner"), " and ", /*#__PURE__*/React.createElement("code", null, "status"), " above carry the role a real system would assign a record, not a claim about who owns Netflix's voice today.")), /*#__PURE__*/React.createElement(ReportSection, {
    id: "engine",
    title: "The engine"
  }, /*#__PURE__*/React.createElement(Finding, {
    measured: "12 dimensions · 4 published research bases · 6 open dependencies",
    verdict: "named"
  }, "Every number on this page was read on the same twelve dimensions: involvement, information density, readability, emotional tone, lexical sophistication, lexical diversity, concreteness, syntactic complexity, directness, cadence, epistemic stance, specificity. Each one implements a published method rather than an invented score."), /*#__PURE__*/React.createElement("p", {
    style: {
      margin: "0 0 1em"
    }
  }, "The run itself is logged under its working name, ", /*#__PURE__*/React.createElement("code", null, "voice_runtime"), ". That's the name inside floor.json and terms.json's own method notes, and it stays unpublished here. The twelve-dimension method it implements ships separately, in the open, under its own name: ", /*#__PURE__*/React.createElement("strong", null, "Word Math"), ", a from-scratch research engine with no Verso code, prompts, or internal implementation details in it. I built Word Math to answer a narrower question than this page asks: not just \"how does this text read,\" but \"can a target voice, the kind a style guide describes in adjectives, be translated into numbers an LLM can be constrained to and a draft can be checked against.\" It fingerprints a text into its twelve scores, translates a target profile into constraints, and validates a draft against that target with a per-dimension delta and a pass or fail. Those three run as a single loop, below."), /*#__PURE__*/React.createElement(DocFigure, {
    caption: "Measure, constrain, validate: the loop Word Math runs, independent of any specific model.",
    source: "Word Math · method"
  }, /*#__PURE__*/React.createElement(Pipeline, {
    steps: [{
      label: "Measure — fingerprint any text into a twelve-dimension reading, 0–10 per dimension."
    }, {
      label: "Constrain — translate a target profile into a system prompt an LLM can be instructed against."
    }, {
      label: "Validate — re-measure the generated draft, and report where it lands outside the target, dimension by dimension."
    }]
  })), /*#__PURE__*/React.createElement(DocFigure, {
    kind: "table",
    caption: "What Word Math is actually built out of, named so it can be checked, not just claimed.",
    source: "Word Math · dependencies"
  }, /*#__PURE__*/React.createElement(Toolchain, {
    items: [{
      name: "spaCy",
      href: "https://spacy.io",
      provides: "Sentence and dependency parsing, the base every other dimension reads from",
      meta: "MIT"
    }, {
      name: "textstat",
      href: "https://pypi.org/project/textstat/",
      provides: "Flesch reading-ease scoring for the readability dimension",
      meta: "MIT"
    }, {
      name: "wordfreq",
      href: "https://github.com/rspeer/wordfreq",
      provides: "Zipf word-frequency lookups for lexical sophistication",
      meta: "Apache-2.0"
    }, {
      name: "lexicalrichness",
      href: "https://pypi.org/project/lexicalrichness/",
      provides: "MTLD scoring for the lexical-diversity dimension",
      meta: "MIT"
    }, {
      name: "pyphen",
      href: "https://pyphen.org/",
      provides: "Offline syllable counting, feeding readability where textstat needs it",
      meta: "GPL-2.0+ / LGPL-2.1+ / MPL-1.1"
    }, {
      name: "en_core_web_sm",
      href: "https://spacy.io/models/en",
      provides: "The English pipeline spaCy runs its parsing through",
      meta: "MIT"
    }],
    label: "Ships today",
    note: "Five of the six carry a clean MIT or Apache-2.0 license. pyphen is the exception: a GPL/LGPL/MPL tri-license, permissive enough to use unmodified as a dependency but not the clean match the other five make. Stated precisely rather than folded into one blanket 'open source' claim, because a license audit that rounds up is the kind of thing this page's own argument says shouldn't happen unrecorded."
  })), /*#__PURE__*/React.createElement(ResearchGrid, {
    columns: 2,
    items: [{
      source: "Biber",
      year: "1988",
      gives: "the involvement-features basis for reading how personal versus detached a text is"
    }, {
      source: "Hyland",
      year: "2005",
      gives: "the hedge/booster lexicons behind epistemic stance"
    }, {
      source: "McCarthy & Jarvis",
      year: "2010",
      gives: "MTLD, the lexical-diversity measure that isn't distorted by text length the way a type-token ratio is"
    }, {
      source: "Flesch",
      year: "1948",
      gives: "the reading-ease formula behind the readability dimension"
    }]
  }), /*#__PURE__*/React.createElement("p", {
    style: {
      margin: "1em 0 0"
    }
  }, "The GitHub release, the engine and the skill that wraps it, lives at ", /*#__PURE__*/React.createElement("a", {
    href: "https://github.com/calebstacy/word-math"
  }, "github.com/calebstacy/word-math"), ".")), /*#__PURE__*/React.createElement(ReportSection, {
    id: "provenance",
    title: "Provenance and limits"
  }, /*#__PURE__*/React.createElement(Finding, {
    verdict: "stated, not implied"
  }, "Everything on this page comes from public, unauthenticated pages, fetched and scored on ", fmtDate(floor.run.date), ". No login, no in-app content, no developer or API documentation, no user-generated content."), /*#__PURE__*/React.createElement(DocFigure, {
    kind: "table",
    caption: "Pages fetched per surface, before either pass sampled or excluded from them.",
    source: "Shared corpus underlying floor.json and terms.json"
  }, /*#__PURE__*/React.createElement(DataTable, {
    variant: "meta",
    columns: ["Surface", "Pages fetched"],
    rows: [["Help Center", "240"], ["Tudum", "240"], ["Marketing", "4"], ["Culture/jobs", "51"]]
  })), /*#__PURE__*/React.createElement("p", {
    style: {
      margin: "0 0 1em"
    }
  }, "The voice-floor reading above scores a sampled subset of that same corpus per surface and string type. The terminology pass mined 534 of the 535 fetched pages directly; the brief that produced it set aside a single culture legal page first. Marketing stays the thin surface throughout this page for the same reason in both passes: Netflix's public marketing footprint is four pages total."), /*#__PURE__*/React.createElement("p", {
    style: {
      margin: "0 0 1em"
    }
  }, "Subtitles were out of scope on purpose, on every pass. They're licensed creative work built by translators, a different discipline from the copy this page reads, and folding them in would measure the wrong thing under the same label."), /*#__PURE__*/React.createElement("p", {
    style: {
      margin: "1.2em 0 0.6em",
      fontWeight: 600
    }
  }, "What the mining pass actually surfaced"), /*#__PURE__*/React.createElement("p", {
    style: {
      margin: "0 0 1em"
    }
  }, "Of 106,948 raw noun chunks the terminology pass extracted, 70.9% survived basic stopword and length filtering, and that is not the same number as \"product-relevant.\" Hand-classifying the 80 highest-frequency surviving concepts found roughly a third, 32.5%, were actual product vocabulary (list, season, series, account, profile); the rest split between ambiguous terms and outright noise: character names, show-recap language, and self-reference from Tudum's entertainment-journalism prose, which supplies 68% of the mined text segments. Seed-family curation focused on the concept families this page reports, rather than a naive top-frequency cut, is what kept the ranked sets above from being mostly plot summary."), /*#__PURE__*/React.createElement("p", {
    style: {
      margin: "0 0 1em"
    }
  }, "At Meta, I ran the same kind of measurement across product surfaces, including Facebook, Messenger, and WhatsApp, as the enforcement layer for an agent that corrected its own drafts before they shipped. This page is a smaller, public-only version of that same idea, built from scratch on my own time against Netflix's own published pages."), /*#__PURE__*/React.createElement(ProvenanceNote, {
    label: "What this method cannot see"
  }, "Nothing behind a login. Nothing served only inside the apps. No developer or partner documentation. No user reviews, forum posts, or social captions. Four public surfaces, read as they present themselves to a visitor who has never signed in.")), /*#__PURE__*/React.createElement(ReportSection, {
    id: "doors",
    title: "Doors deeper"
  }, /*#__PURE__*/React.createElement("p", {
    style: {
      margin: "0 0 1em"
    }
  }, "Five places this page points to, and what's actually there."), /*#__PURE__*/React.createElement(DocFigure, {
    kind: "table",
    wide: true,
    caption: "Where to go from here.",
    source: "Companion pages and documents"
  }, /*#__PURE__*/React.createElement(DataTable, {
    variant: "meta",
    rowHeader: false,
    columns: ["Door", "What's there"],
    rows: [[/*#__PURE__*/React.createElement("a", {
      href: "../papers/two-brands/index.html"
    }, "Netflix and Discord, measured"), "The statistical method this page reuses, run instead as a between-company comparison: the paper that established the test, the correction, and the detection-floor discipline."], [/*#__PURE__*/React.createElement("a", {
      href: "../papers/naming-grammar/index.html"
    }, "A naming grammar for Tudum headlines"), "Tudum's entertainment headlines reverse-engineered into a slot-and-fill grammar, Discord's blog held as a control."], [/*#__PURE__*/React.createElement("a", {
      href: "../papers/governance/index.html"
    }, "Governing a measured voice"), "The full extension-model schema this page instantiates three records from: the shape, a real conflict and its resolution, a self-check loop run against a live draft, and a dependency license audit."], [/*#__PURE__*/React.createElement("a", {
      href: "../../ui_kits/portfolio/index.html#verso"
    }, "Verso"), "The case study this whole approach comes out of: AI content governance work I built and shipped, told without naming what I can't."], [/*#__PURE__*/React.createElement("a", {
      href: "../../ui_kits/portfolio/index.html#resume"
    }, "Résumé"), "Plain orientation to the facts: what I've built, where, and when."]]
  }))), /*#__PURE__*/React.createElement(Endnotes, {
    notes: ["Concreteness runs on a suffix-counting proxy rather than the Brysbaert concreteness norms, and emotional tone runs on an in-house valence lexicon rather than the Warriner valence/arousal/dominance norms. Both are documented limits of the measuring instrument, not corrections applied after the fact. Every score on this page is comparative within this run, not an absolute external scale.", "Help Center's procedural-copy profile (n=54) is a real reading, but it is not a floor: no other Netflix surface reaches five scored procedural batches on any dimension to test it against. It's reported as this surface's own voice, not a cross-surface baseline anything else can be measured against yet.", "All 24 tested heading comparisons land within a hair of this run's own power bar (MDE 0.504–0.506) because Help Center's heading sample sets the ceiling the formula can reach, regardless of which dimension or how much larger Tudum's own sample is. That uniformity is a property of the formula given this sample, not a coincidence in the writing."]
  }), /*#__PURE__*/React.createElement(References, {
    items: [{
      text: "Biber, D. (1988). Variation across Speech and Writing. Cambridge University Press."
    }, {
      text: "Hyland, K. (2005). Metadiscourse: Exploring Interaction in Writing. Continuum."
    }, {
      text: "McCarthy, P. M., & Jarvis, S. (2010). MTLD, vocd-D, and HD-D: A validation study of sophisticated approaches to lexical diversity assessment. Behavior Research Methods, 42(2), 381–392."
    }, {
      text: "Flesch, R. (1948). A new readability yardstick. Journal of Applied Psychology, 32(3), 221–233."
    }, {
      text: "Welch, B. L. (1947). The generalization of ‘Student's’ problem when several different population variances are involved. Biometrika, 34(1–2), 28–35."
    }, {
      text: "Cohen, J. (1988). Statistical Power Analysis for the Behavioral Sciences (2nd ed.). Lawrence Erlbaum Associates."
    }, {
      text: "Benjamini, Y., & Hochberg, Y. (1995). Controlling the false discovery rate: A practical and powerful approach to multiple testing. Journal of the Royal Statistical Society: Series B, 57(1), 289–300."
    }, {
      text: "spaCy: industrial-strength natural language processing in Python.",
      href: "https://spacy.io"
    }]
  }));
}
ReactDOM.createRoot(document.getElementById("root")).render(/*#__PURE__*/React.createElement(App, null));
})();
