/* Generated by tools/build-static.js — compiled ahead of time, do not edit. */

/* ---- plays/netflix (inline script) ---- */
(function () {
const {
  CaseNav,
  CaseSection,
  StoryBeat,
  CaseQuote,
  MetricStrip,
  Eyebrow,
  CardGrid,
  GridCard,
  StageAction,
  ProvenanceNote,
  Panel,
  PanelRow,
  IndexRows
} = window.CalebStacyPortfolioDesignSystem_4a3883;

/* ---------- formatting only — every number below is read from floor.json / terms.json at
   runtime, except two small, clearly-scoped exceptions: a handful of corpus facts (pages
   fetched per surface, the mined-segment share) that live only in floor-notes.md /
   terms-notes.md prose, not as a JSON field; and four numbers from the self-lint trace in
   plays/papers/governance/trace.json (word counts and out-of-band counts for both passes),
   hand-verified against that file rather than fetched live, since it lives outside this
   page's own data directory. Both are cited as such where they appear. ---------- */

const fmtD = d => d === null || d === undefined ? "—" : (d > 0 ? "+" : "") + Number(d).toFixed(2);

/* Hand-verified against plays/papers/governance/trace.json, passes[0] and passes[1]. */
const SELF_LINT = {
  draft1: {
    label: "First draft",
    words: 79,
    outOfBand: 5
  },
  draft2: {
    label: "Revision",
    words: 82,
    outOfBand: 0
  }
};
const NAV_OFFSET = 56;
const STOPS = [{
  id: "overview",
  label: "Overview"
}, {
  id: "move-1",
  label: "Voices"
}, {
  id: "move-2",
  label: "Names"
}, {
  id: "move-3",
  label: "Record"
}, {
  id: "move-4",
  label: "Proof"
}, {
  id: "doors",
  label: "Doors"
}];

/* A quiet quote: the sentence, then a plain small attribution underneath — no border, no
 * ground fill, no mono. The page's normal register carrying a quoted line, nothing more. */
function Quote({
  children,
  attribution,
  style
}) {
  return /*#__PURE__*/React.createElement("figure", {
    style: {
      margin: "18px 0 0",
      maxWidth: 600,
      ...style
    }
  }, /*#__PURE__*/React.createElement("blockquote", {
    style: {
      margin: 0,
      fontFamily: "var(--font-sans)",
      fontSize: "var(--body-size)",
      lineHeight: 1.55,
      color: "var(--story-ink)"
    }
  }, "“", children, "”"), attribution && /*#__PURE__*/React.createElement("figcaption", {
    style: {
      marginTop: 6,
      color: "var(--story-muted)",
      fontFamily: "var(--font-sans)",
      fontSize: 12.5,
      lineHeight: 1.4
    }
  }, attribution));
}

/* The one button shape in the system, doing the "quiet door deeper" the brief asks each move
   to end on. */
function Door({
  href,
  children
}) {
  return /*#__PURE__*/React.createElement("p", {
    style: {
      margin: "clamp(24px,3vw,36px) 0 0"
    }
  }, /*#__PURE__*/React.createElement(StageAction, {
    href: href,
    accent: "signal"
  }, children));
}

/* ---------- app ---------- */

function App() {
  const [data, setData] = React.useState(null);
  const [error, setError] = React.useState(null);
  const scrollRef = React.useRef(null);
  React.useEffect(() => {
    scrollRef.current = document; // this page scrolls at the document level, not a nested pane
  }, []);
  React.useEffect(() => {
    Promise.all([fetch("./floor.json").then(r => {
      if (!r.ok) throw new Error("floor.json HTTP " + r.status);
      return r.json();
    }), fetch("./terms.json").then(r => {
      if (!r.ok) throw new Error("terms.json HTTP " + r.status);
      return r.json();
    })]).then(([floor, terms]) => setData({
      floor,
      terms
    })).catch(e => setError(e.message || String(e)));
  }, []);
  if (error) {
    return /*#__PURE__*/React.createElement("div", {
      className: "errbox"
    }, "Could not load the data files (", error, "). Every number on this page is read from ", /*#__PURE__*/React.createElement("code", null, "floor.json"), " and ", /*#__PURE__*/React.createElement("code", null, "terms.json"), " at runtime. Open this page over a local server, not as a bare file.");
  }
  if (!data) {
    return /*#__PURE__*/React.createElement("div", {
      className: "errbox"
    }, "Loading…");
  }
  const {
    floor,
    terms
  } = data;
  const directness = floor.deviations.filter(d => d.string_type === "body_prose" && d.dimension === "directness");
  const byS = surface => directness.find(d => d.surface === surface);
  const help = byS("help"),
    tudum = byS("tudum");
  const cultureReadability = floor.deviations.find(d => d.string_type === "body_prose" && d.dimension === "readability" && d.surface === "culture");
  const helpProcedural = floor.deviations.find(d => d.string_type === "procedural" && d.surface === "help" && d.dimension === "involvement");
  const getCandidate = id => terms.top_candidates.find(c => c.id === id);
  const contentUnit = getCandidate("content-unit-pairing");
  const myList = getCandidate("save-for-later");
  const seriesEntry = contentUnit.entries.find(e => e.variant === "series");
  const filmEntry = contentUnit.entries.find(e => e.variant === "film");
  const myListEntry = myList.entries.find(e => e.variant === "My List (branded)");
  const cnt = (bySurface, key) => bySurface[key] ? bySurface[key] : 0;
  return /*#__PURE__*/React.createElement("article", {
    style: {
      background: "var(--paper)",
      color: "var(--ink)"
    }
  }, /*#__PURE__*/React.createElement("div", {
    "data-tone": "paper",
    style: {
      padding: "clamp(40px,7vw,84px) var(--gutter) clamp(8px,1.4vw,14px)",
      background: "var(--story-bg)"
    }
  }, /*#__PURE__*/React.createElement(Eyebrow, {
    size: "micro",
    tone: "signal"
  }, "Caleb Stacy")), /*#__PURE__*/React.createElement(CaseNav, {
    scrollRoot: scrollRef,
    stops: STOPS
  }), /*#__PURE__*/React.createElement(CaseSection, {
    id: "overview",
    tone: "paper",
    scrollMarginTop: NAV_OFFSET
  }, /*#__PURE__*/React.createElement(StoryBeat, {
    intro: "I built a tool that measures how writing actually sounds, then ran it against Netflix's own public pages: four surfaces, the same twelve dimensions, 534 pages, nothing behind a login. This is the short version: what the numbers found, and what it takes to hold any of it to a real standard."
  }), /*#__PURE__*/React.createElement(MetricStrip, {
    style: {
      marginTop: "var(--space-7)"
    },
    items: [{
      value: "534",
      label: "public pages measured"
    }, {
      value: "12",
      label: "voice dimensions"
    }, {
      value: "4",
      label: "surfaces"
    }, {
      value: "10",
      label: "records derived"
    }]
  })), /*#__PURE__*/React.createElement(CaseSection, {
    id: "move-1",
    tone: "paper",
    index: "01",
    title: "Voices",
    scrollMarginTop: NAV_OFFSET
  }, /*#__PURE__*/React.createElement(StoryBeat, {
    kicker: "How this was measured",
    title: "Netflix speaks in four public voices.",
    intro: "Help Center, Tudum, the marketing pages, and the careers site are all publicly Netflix, and none of them read quite alike, even measured the same way."
  }), /*#__PURE__*/React.createElement("div", {
    style: {
      margin: "clamp(22px,3vw,34px) 0 0"
    }
  }, /*#__PURE__*/React.createElement(CardGrid, {
    label: "Four surfaces",
    scope: "4",
    columns: 2
  }, /*#__PURE__*/React.createElement(GridCard, {
    label: "01",
    metric: "240",
    title: "Help Center",
    body: "Explains. The only surface with enough how-to writing to score on its own (n=" + helpProcedural.n + "), and the most direct prose in the run."
  }), /*#__PURE__*/React.createElement(GridCard, {
    label: "02",
    metric: "240",
    title: "Tudum",
    body: "Performs. Entertainment journalism about the shows themselves. The richest vocabulary measured, and 68 percent of everything mined for wording."
  }), /*#__PURE__*/React.createElement(GridCard, {
    label: "03",
    metric: "4",
    title: "Marketing",
    body: "Persuades. The homepage, sign-up, and gift cards: four pages, too thin to test with confidence."
  }), /*#__PURE__*/React.createElement(GridCard, {
    label: "04",
    metric: "51",
    title: "Culture",
    body: "Recruits. Careers writing, formal and dense. The largest gap this run measured (readability, " + fmtD(cultureReadability.deviation) + "), and the only surface whose calls to action are capital letters."
  }))), /*#__PURE__*/React.createElement(Door, {
    href: "./full.html"
  }, "How each surface was scored")), /*#__PURE__*/React.createElement(CaseSection, {
    id: "move-2",
    tone: "stage",
    index: "02",
    title: "Names",
    scrollMarginTop: NAV_OFFSET
  }, /*#__PURE__*/React.createElement(StoryBeat, {
    kicker: "Vocabulary and register",
    title: "The same things get different names.",
    intro: "Help and marketing default to “TV show” and “movie.” Tudum and culture reach for “series” and “film” instead, at far higher volume: “series” " + cnt(seriesEntry.counts_by_surface, "tudum") + " times on Tudum against " + cnt(seriesEntry.counts_by_surface, "help") + " on Help, “film” " + cnt(filmEntry.counts_by_surface, "tudum") + " times on Tudum against zero. Same concept, split almost cleanly by surface."
  }), /*#__PURE__*/React.createElement(Quote, {
    attribution: "Help Center, article on subtitles"
  }, "If you watch a TV show or movie that was produced in another region, you may not be able to turn off subtitles."), /*#__PURE__*/React.createElement(Quote, {
    attribution: "Tudum, cast guide for 72 Hours"
  }, "Cherry jumped at the chance to work with Story, whose films he’s long admired."), /*#__PURE__*/React.createElement("p", {
    style: {
      maxWidth: 620,
      margin: "clamp(22px,2.8vw,30px) 0 0",
      color: "var(--story-muted)",
      fontFamily: "var(--font-sans)",
      fontSize: "var(--body-size)",
      lineHeight: 1.55
    }
  }, "“My List” is the counter-example: Netflix's actual feature name, spelled the same everywhere it appears, ", myListEntry.total, " times between Help and Tudum, next to the ", contentUnit.total_occurrences, " occurrences above, split between two names with no public ruling either way."), /*#__PURE__*/React.createElement("p", {
    style: {
      maxWidth: 620,
      margin: "16px 0 0",
      color: "var(--story-muted)",
      fontFamily: "var(--font-sans)",
      fontSize: "var(--body-size)",
      lineHeight: 1.55
    }
  }, "The same split shows up in how a sentence gets written, not just what it's called. Tudum reads measurably less direct than the shared floor the other three surfaces set; Help reads measurably more direct, the opposite way. Culture sits almost as low as Tudum but doesn't clear this run's own bar for a real gap, and Marketing, on four pages, never gets the chance to."), /*#__PURE__*/React.createElement(Door, {
    href: "./full.html#terms"
  }, "All twenty-three ranked term sets"), /*#__PURE__*/React.createElement(Door, {
    href: "./full.html#floor"
  }, "Every dimension, every surface, tested")), /*#__PURE__*/React.createElement(CaseSection, {
    id: "move-3",
    tone: "dark",
    index: "03",
    title: "Record",
    scrollMarginTop: NAV_OFFSET
  }, /*#__PURE__*/React.createElement(StoryBeat, {
    kicker: "The pivot",
    title: "Whether any of this was decided can't be read from out here.",
    intro: "Every surface above has a real reason to sound different — a support page and a careers page aren't writing to the same reader — and Netflix may well have ruled on every one of these differences internally. The public record can't show the ruling. It can show enough to derive one. Here are three of the records this run's own numbers support, written in the shape a governed system would keep them."
  }), /*#__PURE__*/React.createElement(CaseQuote, {
    attribution: "What measurement alone can't settle"
  }, "A measured floor can say a surface moved. It takes a record to say whether it was allowed to."), /*#__PURE__*/React.createElement("div", {
    style: {
      margin: "clamp(22px,2.8vw,30px) 0 0"
    }
  }, /*#__PURE__*/React.createElement(IndexRows, {
    label: "Derived records",
    rows: [{
      id: "term.save-for-later.v1",
      asserts: "“My List” is spelled exactly the same in " + myListEntry.total + " public occurrences across Help and Tudum — behavior indistinguishable from a record already adopted. This record writes down what the surfaces already do, so a draft that reaches for “watchlist” fails before anyone reads it.",
      meta: ["kind: floor", "status: adopted-shaped (observed in the wild)", "owner: terminology owner", "evidence: terms.json · save-for-later"]
    }, {
      id: "extension.body_prose.directness.tudum.v1",
      asserts: "Tudum's body prose reads measurably less direct than the shared floor the other three surfaces set (deviation " + tudum.deviation.toFixed(2) + ", n=" + tudum.n + " against " + tudum.rest_n + "). Editorial has room the floor doesn't grant support writing — an extension is how that room goes on the record instead of staying an accident.",
      meta: ["kind: extension", "status: proposed", "owner: surface voice lead", "evidence: floor.json · tudum/body_prose/directness"]
    }, {
      id: "vocabulary.content_unit.v0",
      asserts: "Help and marketing pair “TV show” with “movie”; Tudum and culture pair “series” with “film” — " + contentUnit.total_occurrences + " occurrences naming what reads like the same thing. This record doesn't pick a winner. It exists so the ruling, whichever way it goes, has somewhere to live. The public product's own shelf and genre names side with “Movies/Shows” 691 to 32.",
      meta: ["kind: vocabulary (proposed shape)", "status: proposed — no owner assigned", "evidence: terms.json · content-unit-pairing", "blocked on: a ruling, not more data"]
    }]
  })), /*#__PURE__*/React.createElement("p", {
    style: {
      maxWidth: 620,
      margin: "clamp(20px,2.6vw,28px) 0 0",
      color: "var(--story-muted)",
      fontFamily: "var(--font-sans)",
      fontSize: "var(--body-size)",
      lineHeight: 1.55
    }
  }, "A record buys a second thing, and it may matter more than the gate: a vocabulary for experiments. \"Would warmer help copy hurt task completion?\" isn't answerable while warm is an adjective. The moment it's a band on a measured dimension, it's an A/B test. Every record above is a governed default today and a testable hypothesis the day someone challenges it."), /*#__PURE__*/React.createElement(ProvenanceNote, {
    label: "What these are",
    style: {
      marginTop: "clamp(20px,2.6vw,28px)"
    }
  }, "Not Netflix's records — nobody at Netflix asked for them, and if an internal ruling exists, reconciling a derived record against it is a diff, not a rewrite. Every number is from this run's public data; a schema shown on invented numbers would be a mockup, not a demonstration."), /*#__PURE__*/React.createElement(Door, {
    href: "./full.html#record"
  }, "The record shape, in full, on this run's numbers")), /*#__PURE__*/React.createElement(CaseSection, {
    id: "move-4",
    tone: "bright",
    index: "04",
    title: "Proof",
    scrollMarginTop: NAV_OFFSET
  }, /*#__PURE__*/React.createElement(StoryBeat, {
    kicker: "The check",
    title: "A record here is something a draft can be checked against.",
    intro: "The records above are more than documentation. Each one is a target: one claim, the evidence behind it, a status that can change — and the moment one is adopted, a draft either lands inside it or doesn't."
  }), /*#__PURE__*/React.createElement("p", {
    style: {
      maxWidth: 660,
      margin: "clamp(20px,2.6vw,28px) 0 0",
      color: "var(--story-ink)",
      fontFamily: "var(--font-sans)",
      fontSize: "var(--body-size)",
      lineHeight: 1.55
    }
  }, "I ran that check once, for real, against the record this project keeps for how directly ordinary prose should read. A first draft missed the target on five of twelve measured dimensions. It read too warm, and it kept dressing up one idea in different words instead of naming it plainly. It stayed vague about what it was actually describing. I rewrote it once. I named the thing the same way throughout, dropped the warm language, and stated two real certainty markers instead of hedging. The second draft landed inside the target on all twelve. Nobody signed off in between; the check ran the moment the second draft existed."), /*#__PURE__*/React.createElement("div", {
    style: {
      overflowX: "auto",
      margin: "clamp(20px,2.6vw,28px) 0 0"
    }
  }, /*#__PURE__*/React.createElement("table", {
    style: {
      borderCollapse: "collapse",
      minWidth: 320,
      fontFamily: "var(--font-sans)",
      fontSize: 13.5
    }
  }, /*#__PURE__*/React.createElement("thead", null, /*#__PURE__*/React.createElement("tr", null, /*#__PURE__*/React.createElement("th", {
    style: {
      textAlign: "left",
      padding: "0 20px 8px 0",
      borderBottom: "1px solid var(--story-line)",
      color: "var(--story-muted)",
      fontWeight: 600
    }
  }, "Draft"), /*#__PURE__*/React.createElement("th", {
    style: {
      textAlign: "left",
      padding: "0 20px 8px",
      borderBottom: "1px solid var(--story-line)",
      color: "var(--story-muted)",
      fontWeight: 600
    }
  }, "Words"), /*#__PURE__*/React.createElement("th", {
    style: {
      textAlign: "left",
      padding: "0 0 8px",
      borderBottom: "1px solid var(--story-line)",
      color: "var(--story-muted)",
      fontWeight: 600
    }
  }, "Outside the target"))), /*#__PURE__*/React.createElement("tbody", null, [SELF_LINT.draft1, SELF_LINT.draft2].map(row => /*#__PURE__*/React.createElement("tr", {
    key: row.label
  }, /*#__PURE__*/React.createElement("td", {
    style: {
      padding: "8px 20px 8px 0",
      borderBottom: "1px solid var(--story-line)",
      color: "var(--story-ink)"
    }
  }, row.label), /*#__PURE__*/React.createElement("td", {
    style: {
      padding: "8px 20px 8px 0",
      borderBottom: "1px solid var(--story-line)",
      color: "var(--story-ink)",
      fontVariantNumeric: "tabular-nums"
    }
  }, row.words), /*#__PURE__*/React.createElement("td", {
    style: {
      padding: "8px 0",
      borderBottom: "1px solid var(--story-line)",
      color: "var(--story-ink)"
    }
  }, row.outOfBand, " of 12")))))), /*#__PURE__*/React.createElement(ProvenanceNote, {
    label: "Where else this has run",
    style: {
      marginTop: "clamp(20px,2.6vw,28px)"
    }
  }, "At Meta, I ran the same kind of check across product surfaces, including Facebook, Messenger, and WhatsApp, as the enforcement layer for an agent that corrected its own drafts before they shipped. This page is the smaller, public-only version, built from scratch on my own time against Netflix's own published pages."), /*#__PURE__*/React.createElement(Door, {
    href: "../papers/governance/index.html"
  }, "The full record shape and self-lint loop")), /*#__PURE__*/React.createElement("div", {
    id: "doors",
    "data-ds": "case-next",
    style: {
      scrollMarginTop: NAV_OFFSET,
      background: "var(--paper)",
      padding: "clamp(40px,6vw,72px) var(--gutter) clamp(56px,8vw,96px)",
      borderTop: "1px solid var(--ink)"
    }
  }, /*#__PURE__*/React.createElement(Eyebrow, {
    size: "micro",
    tone: "signal"
  }, "Doors"), /*#__PURE__*/React.createElement("p", {
    style: {
      maxWidth: 620,
      margin: "10px 0 0",
      color: "var(--ink)",
      fontFamily: "var(--font-sans)",
      fontSize: "var(--subhead-size)",
      fontWeight: 620,
      letterSpacing: "-0.025em"
    }
  }, "Seven places this page points to, if you want more than the walk."), /*#__PURE__*/React.createElement("div", {
    style: {
      marginTop: "clamp(20px,2.6vw,28px)"
    }
  }, /*#__PURE__*/React.createElement(Panel, {
    label: "Where this leads",
    flush: true
  }, [{
    title: "The full index",
    href: "./full.html",
    body: "Every measured cell, every ranked term, the underlying JSON. Nothing summarized."
  }, {
    title: "How Netflix names its shelves",
    href: "../netflix-shelves/index.html",
    body: "A public catalog of shelf, genre, and Top 10 names, read into four deterministic rules and the records they support."
  }, {
    title: "Netflix and Discord, measured",
    href: "../papers/two-brands/index.html",
    body: "Netflix held up against Discord on the same twelve dimensions. That's where this page's method came from."
  }, {
    title: "A naming grammar for Tudum headlines",
    href: "../papers/naming-grammar/index.html",
    body: "Tudum's own headlines, taken apart into the rules that actually generate them."
  }, {
    title: "Governing a measured voice",
    href: "../papers/governance/index.html",
    body: "The record shape in full, plus a real conflict between two records and how it got resolved."
  }, {
    title: "Verso",
    href: "../../ui_kits/portfolio/index.html#verso",
    body: "The Meta project this whole approach grew out of, told without naming what I'm not allowed to."
  }, {
    title: "Word Math",
    href: "https://github.com/calebstacy/word-math",
    body: "The measurement engine on GitHub: the twelve dimensions, the dependencies, the licenses."
  }].map((d, i, arr) => /*#__PURE__*/React.createElement(PanelRow, {
    key: d.title,
    gutter: String(i + 1).padStart(2, "0"),
    last: i === arr.length - 1
  }, /*#__PURE__*/React.createElement(StageAction, {
    href: d.href,
    accent: "signal",
    style: {
      display: "block",
      marginBottom: 4
    }
  }, d.title), /*#__PURE__*/React.createElement("p", {
    style: {
      margin: 0,
      color: "var(--story-muted)",
      fontFamily: "var(--font-sans)",
      fontSize: 13,
      lineHeight: 1.45,
      maxWidth: 520
    }
  }, d.body)))))));
}
ReactDOM.createRoot(document.getElementById("root")).render(/*#__PURE__*/React.createElement(App, null));
})();
