/* Generated by tools/build-static.js — compiled ahead of time, do not edit. */

/* ---- plays/papers/governance (inline script) ---- */
(function () {
const {
  Report,
  ReportSection,
  DocFigure,
  NoteRef,
  Endnotes,
  References,
  Finding,
  DataTable,
  IndexRows,
  Pipeline,
  RuleSplit,
  Toolchain,
  ProvenanceNote,
  VoiceProfile,
  FingerprintBars,
  BeforeAfter,
  EvidenceTrace,
  PullQuote
} = window.CalebStacyPortfolioDesignSystem_4a3883;

/* ---------- formatting only — every number below is read from schema.json / trace.json /
   licence.json at runtime; nothing here is a measurement ---------- */

const DIM_LABEL = {
  involvement: "Involvement",
  information_density: "Information density",
  readability: "Readability",
  emotional_tone: "Emotional tone",
  lexical_sophistication: "Lexical sophistication",
  lexical_diversity: "Lexical diversity",
  concreteness: "Concreteness",
  syntactic_complexity: "Syntactic complexity",
  directness: "Directness",
  cadence: "Cadence",
  epistemic_stance: "Epistemic stance",
  specificity: "Specificity"
};
const DIM_ORDER = Object.keys(DIM_LABEL);
const MONTHS = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
function fmtDate(iso) {
  if (!iso) return "";
  const [y, m, d] = iso.split("-").map(Number);
  return d + " " + MONTHS[m - 1] + " " + y;
}
const fmt = n => n === null || n === undefined ? "—" : Number(n).toFixed(2);
const fmtD = d => d === null || d === undefined ? "—" : (d > 0 ? "+" : "") + Number(d).toFixed(3);
const fmtP = p => {
  if (p === null || p === undefined) return "—";
  if (p < 0.001) return "<0.001";
  return Number(p).toFixed(4);
};
const hi = (value, on) => on ? {
  value,
  highlight: true
} : value;
const getRecord = (schema, id) => schema.records.find(r => r.id === id);
function VerdictText({
  v
}) {
  const on = v === "separates" || v === "adopted";
  return /*#__PURE__*/React.createElement("span", {
    className: "gp-badge " + (on ? "gp-accent" : "gp-muted")
  }, v);
}

/* ---------- app ---------- */

function App() {
  const [data, setData] = React.useState(null);
  const [error, setError] = React.useState(null);
  React.useEffect(() => {
    Promise.all([fetch("./schema.json").then(r => {
      if (!r.ok) throw new Error("schema.json HTTP " + r.status);
      return r.json();
    }), fetch("./trace.json").then(r => {
      if (!r.ok) throw new Error("trace.json HTTP " + r.status);
      return r.json();
    }), fetch("./licence.json").then(r => {
      if (!r.ok) throw new Error("licence.json HTTP " + r.status);
      return r.json();
    })]).then(([schema, trace, licence]) => setData({
      schema,
      trace,
      licence
    })).catch(e => setError(e.message || String(e)));
  }, []);
  if (error) {
    return /*#__PURE__*/React.createElement("div", {
      className: "errbox"
    }, "Could not load the data files (", error, "). Every number on this page is read from ", /*#__PURE__*/React.createElement("code", null, "schema.json"), ", ", /*#__PURE__*/React.createElement("code", null, "trace.json"), ", and ", /*#__PURE__*/React.createElement("code", null, "licence.json"), " at runtime. Open this page over a local server, not as a bare file.");
  }
  if (!data) {
    return /*#__PURE__*/React.createElement("div", {
      className: "errbox"
    }, "Loading…");
  }
  const {
    schema,
    trace,
    licence
  } = data;
  const floorRecords = schema.records.filter(r => r.kind === "floor" && r.status === "adopted" && r.id !== "floor.body_prose.directness.v2");
  const fieldCount = Object.keys(schema.record_shape).length;
  const conflictIds = ["floor.body_prose.directness.v1", "extension.body_prose.directness.editorial.v1", "extension.body_prose.directness.culture-company.v1", "floor.body_prose.directness.v2"];
  const conflictRows = conflictIds.map(id => {
    const r = getRecord(schema, id);
    const ev = r.evidence;
    return [r.id, ev.register, hi(r.status, r.status === "adopted"), fmtD(ev.cohens_d), fmtP(ev.p_adj_bh), /*#__PURE__*/React.createElement(VerdictText, {
      key: "v",
      v: ev.verdict
    })];
  });
  const allRecordRows = schema.records.filter(r => r.evidence).map(r => [r.id, r.kind, hi(r.status, r.status === "adopted"), DIM_LABEL[r.evidence.dimension], fmtD(r.evidence.cohens_d), fmtP(r.evidence.p_adj_bh), fmt(r.evidence.mde_d), /*#__PURE__*/React.createElement(VerdictText, {
    key: "v",
    v: r.evidence.verdict
  })]);
  const refBands = trace.reference_profile.bands;
  const refDims = DIM_ORDER.filter(d => refBands[d]).map(d => ({
    name: DIM_LABEL[d],
    value: Math.round(refBands[d].mean * 10)
  }));
  const [p1, p2] = trace.passes;
  const passTableRows = DIM_ORDER.map(dim => {
    const d1 = p1.dimensions[dim],
      d2 = p2.dimensions[dim];
    const band = d1.band_lo != null ? "[" + fmt(d1.band_lo) + ", " + fmt(d1.band_hi) + "]" : "—";
    return [DIM_LABEL[dim], band, hi(d1.suppressed ? "suppressed" : fmt(d1.score), !d1.suppressed && !d1.in_band), d1.suppressed ? "—" : d1.in_band ? "in band" : "out", fmt(d2.score), d2.in_band ? "in band" : "out"];
  });
  const removedRows = licence.removed.map(it => [it.name, it.licence_issue, it.what_it_did, it.replacement]);
  const blockedRows = licence.blocked_pending_permission.map(b => [b.name, b.size, b.status]);
  return /*#__PURE__*/React.createElement(Report, {
    title: "Governing a measured voice",
    runningHead: "Governing a measured voice — working paper",
    status: "Working paper",
    author: "Caleb Stacy",
    date: fmtDate(schema.generated),
    plain: /*#__PURE__*/React.createElement("p", {
      style: {
        margin: 0
      }
    }, "A tool that can tell you how a piece of writing sounds is only half of a governance system. The other half decides what a given page is allowed to sound like, who signed off on that, and what happens when two approved rules disagree. This paper builds that other half on real writing samples rather than invented ones: a rulebook for four kinds of page, a real example of a rule being narrowed instead of deleted once better evidence came in, a live rewrite of a support reply being checked and corrected against one of those rules, and an audit of what the underlying measuring tool is legally allowed to be built from."),
    subtitle: "An extension-model schema instantiated on real measurements, a self-lint loop run once for real against the engine, and a licence audit of what the engine is built from.",
    abstract: /*#__PURE__*/React.createElement("p", {
      style: {
        margin: 0
      }
    }, schema.records.length, " rule records are shown here, each carrying the exact statistics it was proposed from: a shared floor drawn from where Netflix's and Discord's public writing genuinely reads the same, and per-page-type extensions drawn from where it measurably diverges. Then a self-check loop run once, for real, against the underlying measurement engine, on a sentence written for this page. Then a licence audit of what that engine is legally allowed to be built from. Nothing below is a recommendation to either company; see \"What this page is not saying\" at the end.")
  }, /*#__PURE__*/React.createElement(ReportSection, {
    id: "shape",
    title: "What a governance rule actually looks like"
  }, /*#__PURE__*/React.createElement(Finding, {
    measured: fieldCount + " fields · versioned, scoped, owned, machine-routable",
    verdict: "shared shape"
  }, "Every rule below is stored the same way, whether it applies everywhere or to one kind of page only: a claim, the exact evidence behind it, who is allowed to change it, and what happens to it once better evidence shows up. That shared shape is what lets a piece of writing software and a human reviewer read the same file and agree on what's being claimed."), /*#__PURE__*/React.createElement("p", {
    style: {
      margin: "0 0 1em"
    }
  }, "A rule here is either a ", /*#__PURE__*/React.createElement("em", {
    style: {
      fontStyle: "normal",
      fontWeight: 650
    }
  }, "floor"), " (a default that applies everywhere until something more specific overrides it) or an ", /*#__PURE__*/React.createElement("em", {
    style: {
      fontStyle: "normal",
      fontWeight: 650
    }
  }, "extension"), ", scoped to one kind of page. Both are versioned, owned by a named role rather than a person, and carry a severity: every record on this page is advisory, because every one is a continuous, banded reading rather than a hard pass/fail rule.", /*#__PURE__*/React.createElement(NoteRef, null)), /*#__PURE__*/React.createElement(DocFigure, {
    kind: "table",
    wide: true,
    caption: "Every field a rule record carries, and what each one is for.",
    source: "schema.json · record_shape"
  }, /*#__PURE__*/React.createElement(DataTable, {
    variant: "meta",
    columns: ["Field", "What it carries"],
    rows: Object.entries(schema.record_shape)
  }))), /*#__PURE__*/React.createElement(ReportSection, {
    id: "floor",
    title: "Where the two companies' writing simply agrees"
  }, /*#__PURE__*/React.createElement(Finding, {
    measured: floorRecords.length + " of 4 floor rules shown · adequately powered on every register tested",
    verdict: "real null"
  }, "Four ordinary measures cover everyday page copy: how readable it is, how directly it speaks to the reader, how many hedges and boosters it carries, how much emotion is in it. On all four, Netflix's and Discord's writing reads as statistically indistinguishable. There was enough text collected to be sure, and nothing separated."), /*#__PURE__*/React.createElement("p", {
    style: {
      margin: "0 0 1em"
    }
  }, "Fifteen (page type, dimension) pairs in the underlying measurement run turned out this way. Every one was adequately powered wherever it was tested, and no page-type pair ever separated. Four are shown here as full records. A floor rule's evidence is the one register it was actually measured in; the other registers it was also checked against are corroboration, not folded into one average."), /*#__PURE__*/React.createElement(DocFigure, {
    kind: "table",
    wide: true,
    caption: "The four floor rules in this schema, each backed by the one comparison it was proposed from, not an average of several.",
    source: "schema.json · records[] where kind=floor, status=adopted"
  }, /*#__PURE__*/React.createElement(DataTable, {
    variant: "meta",
    columns: ["Dimension", "Measured in", "Cohen's d", "BH-adj p", "MDE (d)"],
    rows: floorRecords.map(r => [DIM_LABEL[r.evidence.dimension], r.evidence.register, fmtD(r.evidence.cohens_d), fmtP(r.evidence.p_adj_bh), fmt(r.evidence.mde_d)])
  })), /*#__PURE__*/React.createElement(ProvenanceNote, {
    label: "Power rule"
  }, "A cell only backs a rule here if its own minimum detectable effect is at or below a medium effect size: the run's own bar for \"this many samples could reliably find a real gap.\" A handful of rows elsewhere in the underlying run read \"separates\" on too small a sample to trust that label; none of those back a rule on this page.", /*#__PURE__*/React.createElement(NoteRef, null))), /*#__PURE__*/React.createElement(ReportSection, {
    id: "conflict",
    title: "A rule that had to be narrowed, not deleted"
  }, /*#__PURE__*/React.createElement(Finding, {
    measured: "editorial d=" + fmtD(getRecord(schema, "extension.body_prose.directness.editorial.v1").evidence.cohens_d) + " · careers/culture d=" + fmtD(getRecord(schema, "extension.body_prose.directness.culture-company.v1").evidence.cohens_d) + " · both BH-adj p<.0001",
    verdict: "separates"
  }, "A rule proposed after measuring only the help-centre pages said Netflix and Discord write with equal directness everywhere. It wasn't wrong where it was tested. But it was published as if it held everywhere, and it didn't: once the editorial and careers pages were measured the next day, both showed a real, sizeable gap in the same direction. The rule wasn't deleted. It was rewritten to cover only the pages nothing more specific yet reaches."), /*#__PURE__*/React.createElement("p", {
    style: {
      margin: "0 0 1em"
    }
  }, /*#__PURE__*/React.createElement("strong", null, "How a conflict is resolved:"), " ", schema.lifecycle.precedence_rule), /*#__PURE__*/React.createElement(DocFigure, {
    kind: "table",
    wide: true,
    caption: "Directness of ordinary body copy, read in three registers before and after the correction.",
    source: "schema.json · " + conflictIds.join(", ")
  }, /*#__PURE__*/React.createElement(DataTable, {
    variant: "meta",
    columns: ["Record", "Register", "Status", "Cohen's d", "BH-adj p", "Verdict"],
    rows: conflictRows
  })), /*#__PURE__*/React.createElement(DocFigure, {
    caption: "The four stages a rule can be in, walked through on the directness rule above.",
    source: "schema.json · lifecycle"
  }, /*#__PURE__*/React.createElement(Pipeline, {
    steps: [{
      label: "Proposed — " + schema.lifecycle.proposed
    }, {
      label: "Adopted — " + schema.lifecycle.adopted
    }, {
      label: "Versioned — " + schema.lifecycle.versioned
    }, {
      label: "Deprecated — " + schema.lifecycle.deprecated
    }]
  })), /*#__PURE__*/React.createElement(PullQuote, {
    attribution: "How a writing tool actually consumes a rule"
  }, schema.lifecycle.consumption_by_agents)), /*#__PURE__*/React.createElement(ReportSection, {
    id: "split",
    title: "What a check can decide alone, and what still needs a person"
  }, /*#__PURE__*/React.createElement(Finding, {
    measured: "10 checkable rules, sorted",
    verdict: "design decision"
  }, "Whether a draft's reading lands inside a band is arithmetic. A script can decide that alone. Whether a real gap is worth a new rule, whether two active rules actually conflict, whether a boundary was drawn in the right place at all: none of that is arithmetic. Sorting a real rule set this way is what keeps a machine-checkable core small and honest about where it stops."), /*#__PURE__*/React.createElement(DocFigure, {
    kind: "table",
    wide: true,
    caption: "Ten decisions this schema's lifecycle depends on, split by whether a band-check can resolve them alone.",
    source: "schema.json · derived from lifecycle and record_shape"
  }, /*#__PURE__*/React.createElement(RuleSplit, {
    modelLabel: "Still needs a person",
    codeLabel: "A band-check decides alone",
    rules: [{
      kind: "code",
      rule: "Whether a draft's measured reading falls inside a rule's own evidence band"
    }, {
      kind: "model",
      rule: "Whether a real, adequately powered gap is worth a new scoped rule, or noise worth re-testing"
    }, {
      kind: "code",
      rule: "Which rule's scope covers a given (page type, dimension, surface)"
    }, {
      kind: "model",
      rule: "Whether two adopted rules with overlapping scope are a real conflict or measuring different things"
    }, {
      kind: "code",
      rule: "Whether a more specific active rule exists and should take precedence over the floor"
    }, {
      kind: "model",
      rule: "Whether a floor's claim should be narrowed in scope or the underlying band reconsidered"
    }, {
      kind: "code",
      rule: "Whether a cell's own minimum detectable effect clears the power bar before it can back a rule"
    }, {
      kind: "model",
      rule: "Whether a proposed rule ships as advisory or gets escalated toward a hard, deterministic check"
    }, {
      kind: "code",
      rule: "Whether a cited rule id is deprecated, and where it points instead"
    }, {
      kind: "model",
      rule: "Whether the page-type boundaries this schema draws are the right boundaries at all"
    }],
    note: "A band-check is cheap and can run on every draft a writing tool produces. Everything on the left is why 'adopted' is a status a role sets, not a threshold a script crosses on its own."
  }))), /*#__PURE__*/React.createElement(ReportSection, {
    id: "records",
    title: "Every rule this schema instantiates"
  }, /*#__PURE__*/React.createElement(Finding, {
    measured: schema.records.length + " full records shown, of 24 qualifying pairs the underlying run could support",
    verdict: "coverage"
  }, "Ten rules are shown here in full, chosen to walk through every stage a rule can be in and the one real conflict, on real numbers rather than a curated best case."), /*#__PURE__*/React.createElement(DocFigure, {
    kind: "table",
    wide: true,
    caption: "Every rule record in this schema: what it claims, its status, and the statistics behind it.",
    source: "schema.json · records[]"
  }, /*#__PURE__*/React.createElement(DataTable, {
    variant: "meta",
    columns: ["Record", "Kind", "Status", "Dimension", "d", "p (BH-adj)", "MDE (d)", "Verdict"],
    rows: allRecordRows
  })), /*#__PURE__*/React.createElement("p", {
    style: {
      margin: 0,
      color: "var(--story-muted)"
    }
  }, "A floor rule's \"no meaningful difference\" reading above is not a weaker result than \"separates.\" It reflects what an adequately powered comparison looks like when nothing actually separated. The verdict column is the underlying statistics run's own classification; this schema's status and severity fields are a separate, human-reviewed layer on top of it.")), /*#__PURE__*/React.createElement(ReportSection, {
    id: "selflint",
    title: "Watching one rule get enforced, in real time"
  }, /*#__PURE__*/React.createElement(Finding, {
    measured: trace.passes_to_converge + " passes to converge · " + p1.out_of_band.length + " of 12 dimensions missed on pass 1 · " + p2.out_of_band.length + " on pass 2",
    verdict: trace.converged ? "converged" : "did not converge"
  }, "A support-reply draft was written and measured against Discord's own help-centre band. It missed on five of twelve measures. It read as warm customer-service copy where the band expected something plainer and more specific. It was rewritten once and re-measured. The second draft landed inside every band. That two-step loop is the entire check a writing tool would run before a draft ships."), /*#__PURE__*/React.createElement("p", {
    style: {
      margin: "0 0 1em"
    }
  }, trace.draft_never_shipped_copy, " The band it's checked against is the same evidence cell the directness rule above cites: ", /*#__PURE__*/React.createElement("strong", null, trace.reference_profile.label), " (", trace.reference_profile.cell, "), ", trace.reference_profile.power.n_items_scored, " items scored. The engine parsing it is spaCy's ", /*#__PURE__*/React.createElement("code", null, trace.engine.spacy_model), " pipeline,", /*#__PURE__*/React.createElement(NoteRef, null), " and readability specifically is scored with the Flesch reading-ease formula.", /*#__PURE__*/React.createElement(NoteRef, null)), /*#__PURE__*/React.createElement(DocFigure, {
    caption: "The band a draft for Discord Support body prose is checked against, on all twelve measured dimensions.",
    source: "trace.json · reference_profile.bands"
  }, /*#__PURE__*/React.createElement(VoiceProfile, {
    product: "Discord",
    surface: trace.reference_profile.label,
    dimensions: refDims,
    notes: [{
      name: "Concreteness",
      why: "The highest-scoring dimension in this register at " + fmt(refBands.concreteness.mean) + "/10. Troubleshooting prose names the object and the fix rather than describing them abstractly."
    }, {
      name: "Emotional tone",
      why: "The lowest-scoring dimension at " + fmt(refBands.emotional_tone.mean) + "/10, a cool, low-affect register. That is exactly what pass 1 below violates first."
    }]
  })), /*#__PURE__*/React.createElement(ReportSection, {
    level: 2,
    id: "passes",
    title: "Two passes, drawn against the band"
  }, /*#__PURE__*/React.createElement(Finding, {
    measured: "pass 1: " + p1.out_of_band.map(d => DIM_LABEL[d]).join(", "),
    verdict: "revised"
  }, "The first draft leaned on warm, varied customer-service language: \"good news,\" \"friendly,\" the same idea dressed in five different words. That pushed it out of band on emotional tone, word variety, and word rarity at once. The second draft names the same object the same way every time and states two plain certainty markers instead."), /*#__PURE__*/React.createElement("div", {
    style: {
      overflowX: "auto"
    }
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      display: "grid",
      gridTemplateColumns: "1fr 1fr",
      gap: "clamp(16px,3vw,32px)"
    }
  }, /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement("p", {
    style: {
      margin: "0 0 8px",
      fontFamily: "var(--font-mono)",
      fontSize: 9,
      fontWeight: 700,
      color: "var(--story-muted)"
    }
  }, "Pass 1 · draft_v1 · ", p1.out_of_band.length, " of 12 outside band"), /*#__PURE__*/React.createElement(FingerprintBars, {
    dimensions: DIM_ORDER.map(d => {
      const x = p1.dimensions[d];
      return x.suppressed ? null : {
        name: DIM_LABEL[d],
        value: x.score,
        band: [x.band_lo, x.band_hi]
      };
    }).filter(Boolean),
    scale: 10,
    showBand: true
  })), /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement("p", {
    style: {
      margin: "0 0 8px",
      fontFamily: "var(--font-mono)",
      fontSize: 9,
      fontWeight: 700,
      color: "var(--story-muted)"
    }
  }, "Pass 2 · draft_v2 · ", p2.out_of_band.length, " of 12 outside band"), /*#__PURE__*/React.createElement(FingerprintBars, {
    dimensions: DIM_ORDER.map(d => {
      const x = p2.dimensions[d];
      return x.suppressed ? null : {
        name: DIM_LABEL[d],
        value: x.score,
        band: [x.band_lo, x.band_hi]
      };
    }).filter(Boolean),
    scale: 10,
    showBand: true
  })))), /*#__PURE__*/React.createElement(DocFigure, {
    caption: "The revision itself, with what moved between drafts and why.",
    source: "trace.json · passes[1].text, passes[1].changes_from_prior"
  }, /*#__PURE__*/React.createElement(BeforeAfter, {
    before: p1.text,
    after: p2.text,
    beforeLabel: "draft_v1 · " + p1.out_of_band.length + " out of band",
    afterLabel: "draft_v2 · converged",
    deltas: p1.out_of_band.map(dim => ({
      name: DIM_LABEL[dim],
      from: fmt(p1.dimensions[dim].score),
      to: fmt(p2.dimensions[dim].score)
    }))
  })), /*#__PURE__*/React.createElement(DocFigure, {
    caption: "The full trail, from reference band to converged draft.",
    source: "trace.json · passes[]"
  }, /*#__PURE__*/React.createElement(EvidenceTrace, {
    steps: [{
      step: "Reference loaded",
      detail: "The " + trace.reference_profile.label + " cell's mean and spread per dimension, from an adopted floor rule's own evidence."
    }, {
      step: "Draft 1 written and measured",
      detail: p1.n_words + " words, scored on all twelve dimensions. " + p1.out_of_band.length + " fell outside band: " + p1.out_of_band.map(d => DIM_LABEL[d]).join(", ") + "."
    }, {
      step: "Revised",
      detail: p2.changes_from_prior.reasoning.split(". ")[0] + "."
    }, {
      step: "Draft 2 measured",
      detail: p2.n_words + " words. " + (p2.out_of_band.length === 0 ? "All twelve dimensions landed inside band." : p2.out_of_band.length + " still outside band.")
    }, {
      step: trace.converged ? "Converged" : "Did not converge",
      detail: "Two passes total. " + (trace.converged ? "This is the self-check loop a writing tool runs end to end, on one real rule." : "A third pass would be required, shown here as a failure rather than smoothed over.")
    }]
  })), /*#__PURE__*/React.createElement(DocFigure, {
    kind: "table",
    wide: true,
    caption: "Every dimension, both passes, against the band.",
    source: "trace.json · passes[0].dimensions, passes[1].dimensions"
  }, /*#__PURE__*/React.createElement(DataTable, {
    variant: "meta",
    columns: ["Dimension", "Band (mean ± 1 spread)", "Pass 1", "Pass 1 verdict", "Pass 2", "Pass 2 verdict"],
    rows: passTableRows
  })))), /*#__PURE__*/React.createElement(ReportSection, {
    id: "licence",
    title: "What the measuring instrument is legally allowed to run on"
  }, /*#__PURE__*/React.createElement(Finding, {
    measured: licence.shipped.length + " shipped · " + licence.removed.length + " removed on licence grounds · " + licence.blocked_pending_permission.length + " blocked pending permission",
    verdict: "audit"
  }, "The engine ships on six open packages today. Three more were tried and pulled before shipping, not because they didn't work but because their licences would have forced the whole product under terms it can't accept, or because commercial use of the data they bundle requires a payment nobody has made. Four more useful datasets sit unused for the same reason: permission was never even asked for."), /*#__PURE__*/React.createElement("p", {
    style: {
      margin: "0 0 1em"
    }
  }, licence.framing), /*#__PURE__*/React.createElement(DocFigure, {
    caption: "What ships today.",
    source: "licence.json · shipped"
  }, /*#__PURE__*/React.createElement(Toolchain, {
    items: licence.shipped,
    label: "Ships today",
    note: licence.removed.length + " dependencies were cut before shipping, on licence grounds rather than a functionality gap. " + licence.blocked_pending_permission.length + " data sources remain blocked pending the authors' commercial-use permission."
  })), /*#__PURE__*/React.createElement(DocFigure, {
    kind: "table",
    wide: true,
    caption: "What was tried and removed, and the licence reason for each.",
    source: "licence.json · removed"
  }, /*#__PURE__*/React.createElement(DataTable, {
    variant: "meta",
    columns: ["Package", "Licence issue", "What it did", "Replacement"],
    rows: removedRows
  })), /*#__PURE__*/React.createElement(DocFigure, {
    kind: "table",
    caption: "Not installed at all, named here because a real audit lists what it chose not to use as well as what it removed.",
    source: "licence.json · blocked_pending_permission"
  }, /*#__PURE__*/React.createElement(DataTable, {
    variant: "meta",
    columns: ["Data source", "Size", "Status"],
    rows: blockedRows
  })), /*#__PURE__*/React.createElement(ProvenanceNote, {
    label: "Unaudited addition — " + licence.unaudited_addition.name
  }, licence.unaudited_addition.note), /*#__PURE__*/React.createElement(PullQuote, {
    attribution: "The general rule",
    style: {
      marginTop: "var(--space-8)"
    }
  }, licence.general_rule)), /*#__PURE__*/React.createElement(ReportSection, {
    id: "verdict",
    title: "What this page is not saying"
  }, /*#__PURE__*/React.createElement(Finding, {
    verdict: "descriptive"
  }, "Nothing here is advice to Netflix or Discord about what their writing should sound like. Both companies' own public pages are simply the only real numbers available to build and test a rulebook like this on. The rulebook mechanism is the actual subject of this paper, not a critique of either company's voice."), /*#__PURE__*/React.createElement("p", {
    style: {
      margin: 0
    }
  }, "The floor and extension rules above are read off language both companies already publish, at whatever statistical power the underlying run actually reached. Where a page-type pair was too small to trust, no rule was built on it; none was softened into one anyway."), /*#__PURE__*/React.createElement(ProvenanceNote, {
    label: "Nothing from an employer"
  }, "No internal tool names, internal figures, or real rule identifiers appear anywhere on this page. Every id above is a schema shape built for this demonstration, on public writing, measured after the fact.")), /*#__PURE__*/React.createElement(Endnotes, {
    notes: ["Cells excluded on power grounds despite reading “separates” in the raw statistics: a Tudum procedural-copy cell at n=3 vs n=26, the help-centre heading cells at a detectable-effect size of 0.544–0.545 across all twelve dimensions (n=38 vs 87–88), and a marketing lexical-sophistication cell at 0.894 (n=13 vs 40). None of the three back a rule on this page.", "en_core_web_trf replaces en_core_web_sm, the engine's documented fallback. trf is markedly stronger at the dependency parsing and named-entity recognition that syntactic complexity, involvement, and specificity read from.", "Two dimensions on this page are known approximations rather than published norms: emotional tone runs on an in-house valence list rather than the Warriner valence/arousal/dominance norms, and concreteness is a suffix-counting proxy rather than the Brysbaert concreteness norms. Scores are comparative within this run, not an absolute external scale."]
  }), /*#__PURE__*/React.createElement(References, {
    items: [{
      text: "Flesch, R. (1948). A new readability yardstick. Journal of Applied Psychology, 32(3), 221–233."
    }, {
      text: "Warriner, A. B., Kuperman, V., & Brysbaert, M. (2013). Norms of valence, arousal, and dominance for 13,915 English lemmas. Behavior Research Methods, 45, 1191–1207."
    }, {
      text: "Brysbaert, M., Warriner, A. B., & Kuperman, V. (2014). Concreteness ratings for 40 thousand generally known English word lemmas. Behavior Research Methods, 46, 904–911."
    }, {
      text: "spaCy: industrial-strength natural language processing in Python.",
      href: "https://spacy.io"
    }]
  }));
}
ReactDOM.createRoot(document.getElementById("root")).render(/*#__PURE__*/React.createElement(App, null));
})();
