/* Generated by tools/build-static.js — compiled ahead of time, do not edit. */

/* ---- plays/netflix-shelves (inline script) ---- */
(function () {
const {
  Eyebrow,
  ProvenanceNote
} = window.CalebStacyPortfolioDesignSystem_4a3883;

/* ---------- the live terminal ----------
   Nothing on this page simulates the instrument any more. The window below is
   shelftool.py itself — a fresh process per connection, in a PTY on the demo box,
   streamed here over a secure websocket. The red ident, the boot facts, the open
   ledger while the agent thinks: all of it happens inside that process, because
   that is where it really happens. This file only frames it: a connect gate (a
   session is a real process on a small machine, so it starts on request, not on
   page load), a liveness probe, and an honest offline state. */

const TERMINAL_URL = "https://5-161-60-100.sslip.io/";
const SESSION_MINUTES = 30;
const AGENT_ASKS = 12;
const AGENT_MODEL = "claude-opus-5";
const REDUCED_MOTION = window.matchMedia && window.matchMedia("(prefers-reduced-motion: reduce)").matches;
/* ttyd forwards URL args to the CLI (allowlisted server-side); --plain skips the
   animated ident, so reduced motion carries through to the real process. */
const SESSION_SRC = REDUCED_MOTION ? TERMINAL_URL + "?arg=--plain" : TERMINAL_URL;
function Line({
  tone,
  children
}) {
  const color = tone === "muted" ? "var(--stage-muted)" : tone === "signal" ? "var(--signal-stage)" : "var(--stage-ink)";
  return /*#__PURE__*/React.createElement("div", {
    style: {
      color,
      whiteSpace: "pre-wrap",
      wordBreak: "break-word",
      maxWidth: 640
    }
  }, children);
}
function App() {
  const [probe, setProbe] = React.useState("checking"); // checking | live | down
  const [connected, setConnected] = React.useState(false);
  const [session, setSession] = React.useState(1); // bumping remounts the iframe → fresh process
  const frameRef = React.useRef(null);
  React.useEffect(() => {
    let alive = true;
    const ctrl = new AbortController();
    const timer = setTimeout(() => ctrl.abort(), 5000);
    /* no-cors: an opaque response proves the box answered; a network error means
       it didn't. That is all the page needs to know. */
    fetch(TERMINAL_URL, {
      mode: "no-cors",
      cache: "no-store",
      signal: ctrl.signal
    }).then(() => {
      if (alive) setProbe("live");
    }).catch(() => {
      if (alive) setProbe("down");
    }).finally(() => clearTimeout(timer));
    return () => {
      alive = false;
      ctrl.abort();
    };
  }, []);
  const connect = () => {
    setConnected(true);
    setTimeout(() => {
      if (frameRef.current) frameRef.current.focus();
    }, 600);
  };
  const restart = () => {
    setSession(n => n + 1);
    setTimeout(() => {
      if (frameRef.current) frameRef.current.focus();
    }, 600);
  };
  const statusLabel = probe === "checking" ? "checking the box…" : probe === "down" ? "offline" : connected ? "live session" : "live · one process per visitor";
  return /*#__PURE__*/React.createElement("article", {
    style: {
      background: "var(--paper)",
      color: "var(--ink)",
      minHeight: "100vh"
    }
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      padding: "clamp(32px,5vw,56px) var(--gutter) clamp(48px,7vw,84px)",
      maxWidth: 900
    }
  }, /*#__PURE__*/React.createElement(Eyebrow, {
    size: "micro",
    tone: "signal"
  }, "Caleb Stacy · shelf catalog"), /*#__PURE__*/React.createElement("h1", {
    style: {
      margin: "12px 0 0",
      fontFamily: "var(--font-sans)",
      fontSize: "clamp(26px,3vw,38px)",
      fontWeight: 700,
      lineHeight: 1.08,
      letterSpacing: "-0.045em"
    }
  }, "Ask the records"), /*#__PURE__*/React.createElement("p", {
    style: {
      margin: "12px 0 0",
      maxWidth: 640,
      color: "var(--story-muted)",
      fontFamily: "var(--font-sans)",
      fontSize: "var(--lede-size)",
      lineHeight: 1.45,
      letterSpacing: "-0.025em"
    }
  }, /*#__PURE__*/React.createElement("a", {
    href: "./index.html",
    style: {
      color: "inherit"
    }
  }, "The working paper"), " reads Netflix's public shelf names into four records and a map of their rhetoric. The terminal below is those records' own CLI, running for real: connecting boots a fresh ", /*#__PURE__*/React.createElement("a", {
    href: "./shelftool.py",
    style: {
      color: "inherit"
    }
  }, "shelftool.py"), " process on a small server and streams it into this page. Commands answer by computation, identically for everyone; anything else goes to a Claude agent that cites only what the same tools count. It runs on my key, questions on the house up to a point; ", /*#__PURE__*/React.createElement("span", {
    style: {
      fontFamily: "var(--font-mono)",
      fontSize: "0.85em"
    }
  }, "key sk-ant-…"), " inside the terminal swaps in yours."), /*#__PURE__*/React.createElement("div", {
    style: {
      marginTop: "clamp(22px,3vw,34px)",
      border: "1px solid var(--ink)",
      background: "var(--stage-deep)",
      boxShadow: "var(--story-shadow)"
    }
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      display: "flex",
      justifyContent: "space-between",
      gap: 12,
      alignItems: "baseline",
      padding: "10px 16px",
      borderBottom: "1px solid var(--stage-line)"
    }
  }, /*#__PURE__*/React.createElement("span", {
    style: {
      color: "var(--stage-muted)",
      fontFamily: "var(--font-mono)",
      fontSize: 9,
      fontWeight: 700
    }
  }, "shelf tool — live terminal"), /*#__PURE__*/React.createElement("span", {
    style: {
      display: "flex",
      gap: 14,
      alignItems: "baseline"
    }
  }, connected && probe === "live" && /*#__PURE__*/React.createElement("button", {
    type: "button",
    className: "term-chip",
    onClick: restart
  }, "new session"), probe === "live" && /*#__PURE__*/React.createElement("a", {
    className: "term-chip",
    style: {
      textDecoration: "none"
    },
    href: SESSION_SRC,
    target: "_blank",
    rel: "noopener"
  }, "full screen ↗"), /*#__PURE__*/React.createElement("span", {
    style: {
      color: probe === "down" ? "var(--signal-stage)" : "var(--stage-muted)",
      fontFamily: "var(--font-mono)",
      fontSize: 9,
      fontWeight: 700
    }
  }, statusLabel))), /*#__PURE__*/React.createElement("div", {
    className: "term-body"
  }, /*#__PURE__*/React.createElement("div", {
    className: "term-stage"
  }, connected && probe === "live" ? /*#__PURE__*/React.createElement("iframe", {
    key: session,
    ref: frameRef,
    className: "term-frame",
    src: SESSION_SRC,
    title: "Shelf Tool — live terminal session",
    allow: "clipboard-write",
    referrerPolicy: "no-referrer"
  }) : /*#__PURE__*/React.createElement("div", {
    className: "term-cover"
  }, probe === "down" ? /*#__PURE__*/React.createElement(React.Fragment, null, /*#__PURE__*/React.createElement(Line, {
    tone: "signal"
  }, "the terminal box is offline right now"), /*#__PURE__*/React.createElement(Line, {
    tone: "muted"
  }, "nothing simulated stands in for it; when the process can't run, the page says so"), /*#__PURE__*/React.createElement(Line, {
    tone: "muted"
  }, "the CLI itself runs anywhere: ", /*#__PURE__*/React.createElement("a", {
    className: "term-a",
    href: "./shelftool.py"
  }, "shelftool.py"), " from this directory, with uv. same records; the agent takes your own key"), /*#__PURE__*/React.createElement(Line, {
    tone: "muted"
  }, "the records stay readable without it: ", /*#__PURE__*/React.createElement("a", {
    className: "term-a",
    href: "./index.html"
  }, "the working paper"), " · ", /*#__PURE__*/React.createElement("a", {
    className: "term-a",
    href: "./shelves.json"
  }, "shelves.json"), " · ", /*#__PURE__*/React.createElement("a", {
    className: "term-a",
    href: "./moves.json"
  }, "moves.json"))) : /*#__PURE__*/React.createElement(React.Fragment, null, /*#__PURE__*/React.createElement(Line, null, "connecting boots a fresh process, ident and all, and hands you the prompt"), /*#__PURE__*/React.createElement(Line, {
    tone: "muted"
  }, "one live process per visitor · " + SESSION_MINUTES + "-minute session · " + AGENT_ASKS + " agent asks on the house key, and the commands never run out"), /*#__PURE__*/React.createElement(Line, {
    tone: "muted"
  }, "check a draft name against the records, or talk the agent through a title idea"), /*#__PURE__*/React.createElement("button", {
    type: "button",
    className: "term-connect",
    onClick: connect,
    disabled: probe !== "live"
  }, probe === "checking" ? "checking the box…" : "▸ connect")))))), /*#__PURE__*/React.createElement("div", {
    className: "term-hint"
  }, "inside the terminal, type help. or try: moves · lane kids · check Cozy british mysteries and tv thrillers · family horror"), /*#__PURE__*/React.createElement("div", {
    style: {
      marginTop: "clamp(26px,3.6vw,40px)",
      maxWidth: 660
    }
  }, /*#__PURE__*/React.createElement(ProvenanceNote, {
    label: "What this is"
  }, "A real instance, not a simulation. The window above is shelftool.py running in a PTY on a small server, streamed here over a secure websocket. Each connection gets its own process, ", SESSION_MINUTES, " minutes long. Its commands compute every answer from shelves.json and moves.json, the same files this site publishes, using the same definitions the original crawl used; on boot, it recounts everything and confirms it still matches. The agent is Claude (", AGENT_MODEL, ") under my API key, good for ", AGENT_ASKS, " asks per session; key sk-ant-… inside the terminal connects your own instead, held in that session's memory only. The agent's prose is a model's; its counts come from the same tools that answer everywhere else on this page, and it's instructed to claim nothing about Netflix beyond what the crawl shows. Nothing here is Netflix policy, nothing behind a login was touched, and this page is not affiliated with Netflix; ", /*#__PURE__*/React.createElement("a", {
    href: "./index.html"
  }, "the paper"), " carries the full method."))));
}
ReactDOM.createRoot(document.getElementById("root")).render(/*#__PURE__*/React.createElement(App, null));
})();
