/* Generated by tools/build-static.js — compiled ahead of time, do not edit. */

/* ---- plays/netflix-shelves (inline script) ---- */
(function () {
const {
  RegistrationMark
} = window.CalebStacyPortfolioDesignSystem_4a3883;
function validateFixture(value) {
  const isText = item => typeof item === "string" && item.trim().length > 0;
  const isHash = item => typeof item === "string" && /^[0-9a-f]{64}$/.test(item);
  const isCount = item => Number.isInteger(item) && item >= 0;
  const recordedRequest = "Review this exact proposed shelf title for a straightforward collection of classic anime: ‘Classic Anime Films’. Check that exact string against the adopted demo profile. If it returns for review, revise it, check the revised exact string again, and only then recommend the final title. Show a compact audit trail with the exact input, first check result, exact revision, second check result, and exact final title.";
  if (!value || value.request !== recordedRequest) return false;
  if (!Array.isArray(value.drafts) || value.drafts.length !== 2) return false;
  if (!Array.isArray(value.final_titles) || value.final_titles.length !== 2 || !value.final_titles.every(isText)) return false;
  if (!value.recorded_model || !value.terminology_evidence || !value.technical || !value.technical.policy) return false;
  if (!isText(value.technical.policy.version) || !isHash(value.technical.policy.hash)) return false;
  if (!Array.isArray(value.technical.receipts) || value.technical.receipts.length !== value.drafts.length) return false;
  const [first, second] = value.drafts;
  const model = value.recorded_model;
  const evidence = value.terminology_evidence;
  if (!first || !second || !isText(first.draft) || !isText(second.draft)) return false;
  if (!Array.isArray(first.checks) || first.checks.length !== 2 || !Array.isArray(second.checks) || second.checks.length !== 1) return false;
  if (!first.checks[0] || first.checks[0].result !== "REVIEW" || !Array.isArray(first.checks[0].findings) || first.checks[0].findings.length !== 1) return false;
  if (!isText(first.checks[0].findings[0].message) || first.checks[0].findings[0].proposed_title !== model.revision) return false;
  if (!first.what_changed || first.what_changed.before !== first.draft || first.what_changed.after !== model.revision) return false;
  if (!first.checked_again || first.checked_again.title !== model.revision || first.checked_again.result !== "PASS") return false;
  if (first.final_title !== model.final_recommendation || model.final_recommendation !== model.revision || value.final_titles[0] !== first.final_title) return false;
  if (second.checks[0].result !== "PASS" || second.final_title !== second.draft || value.final_titles[1] !== second.final_title) return false;
  if (model.input_title !== first.draft || model.input_role !== "provided to the agent" || model.revision_role !== "authored by the model") return false;
  if (!isText(model.model) || !isText(model.capture_date) || !isHash(model.prompt_sha256) || !isHash(model.response_sha256) || model.reported_tool_call_count !== 4) return false;
  if (model.prompt_sha256 !== "f64e7be2eb32985edb574c4399d03f544b72179419632cd88740f01ca1670ed4") return false;
  if (model.response_sha256 !== "85d7261b018c8998c3e8467fc324b90bb19a6a353af414a3fa3154c05a1a6696") return false;
  if (evidence.rule_id !== "movie-show-terminology" || evidence.adoption_status !== "adopted_for_demo") return false;
  if (evidence.first_check_status !== "REVIEW" || evidence.second_check_status !== "PASS") return false;
  if (![evidence.movie_show_family_count, evidence.series_film_family_count, evidence.sample_count, evidence.retained_counterexample_count].every(isCount)) return false;
  if (!Array.isArray(evidence.retained_counterexamples) || evidence.retained_counterexample_count !== evidence.retained_counterexamples.length || !evidence.retained_counterexamples.every(isText)) return false;
  if (!evidence.scope || !isText(evidence.scope.when) || !isText(evidence.adoption_decision)) return false;
  return value.technical.receipts.every(receipt => receipt && isText(receipt.draft_id) && isHash(receipt.source_text_hash) && Array.isArray(receipt.check_text_hashes) && receipt.check_text_hashes.length > 0 && receipt.check_text_hashes.every(isHash) && isHash(receipt.final_text_hash));
}
window.__netflixShelfDemoValidateFixture = validateFixture;
function Result({
  value
}) {
  const tone = value === "PASS" ? "result-pass" : "result-review";
  return /*#__PURE__*/React.createElement("span", {
    className: "result " + tone
  }, value);
}
function FullReceipt({
  fixture
}) {
  return /*#__PURE__*/React.createElement("details", null, /*#__PURE__*/React.createElement("summary", null, "Inspect hashes and recorded exchange"), /*#__PURE__*/React.createElement("dl", null, /*#__PURE__*/React.createElement("dt", null, "Profile hash"), /*#__PURE__*/React.createElement("dd", null, fixture.technical.policy.hash), /*#__PURE__*/React.createElement("dt", null, "Recorded prompt hash"), /*#__PURE__*/React.createElement("dd", null, fixture.recorded_model.prompt_sha256), /*#__PURE__*/React.createElement("dt", null, "Visible response hash"), /*#__PURE__*/React.createElement("dd", null, fixture.recorded_model.response_sha256), fixture.technical.receipts.map(receipt => /*#__PURE__*/React.createElement(React.Fragment, {
    key: receipt.draft_id
  }, /*#__PURE__*/React.createElement("dt", null, receipt.draft_id + " · source → checks → final"), /*#__PURE__*/React.createElement("dd", null, [receipt.source_text_hash, ...receipt.check_text_hashes, receipt.final_text_hash].join(" → ")))), /*#__PURE__*/React.createElement("dt", null, "Public record"), /*#__PURE__*/React.createElement("dd", null, /*#__PURE__*/React.createElement("a", {
    href: "./recorded_agent_trace.json"
  }, "Exact prompt and visible answer"))));
}
function Demo({
  fixture
}) {
  const first = fixture.drafts[0];
  const second = fixture.drafts[1];
  const evidence = fixture.terminology_evidence;
  const model = fixture.recorded_model;
  return /*#__PURE__*/React.createElement("main", null, /*#__PURE__*/React.createElement("section", {
    className: "demo-stage",
    "data-tone": "stage",
    "aria-labelledby": "demo-title"
  }, /*#__PURE__*/React.createElement(RegistrationMark, {
    className: "stage-register",
    size: 28,
    style: {
      top: "auto",
      bottom: 30,
      right: 30,
      opacity: 0.42
    }
  }), /*#__PURE__*/React.createElement("div", {
    className: "demo-wrap"
  }, /*#__PURE__*/React.createElement("header", {
    className: "demo-mast"
  }, /*#__PURE__*/React.createElement("p", {
    className: "demo-ident"
  }, /*#__PURE__*/React.createElement("strong", null, "Caleb Stacy"), " · Shelf title proof"), /*#__PURE__*/React.createElement("p", {
    className: "demo-ident"
  }, "Recorded exchange · Independent checks")), /*#__PURE__*/React.createElement("div", {
    className: "demo-intro"
  }, /*#__PURE__*/React.createElement("h1", {
    id: "demo-title"
  }, "The final string has to meet the rule—not just the prompt."), /*#__PURE__*/React.createElement("div", {
    className: "demo-intro-copy"
  }, /*#__PURE__*/React.createElement("p", null, "I gave a live agent ", /*#__PURE__*/React.createElement("strong", null, "Classic Anime Films"), ". The adopted demo profile returned the title for review; the model changed one word; code checked the revision before this page could display it. The profile comes only from public Netflix shelf names—not Netflix policy."), /*#__PURE__*/React.createElement("p", null, "The check happens after generation, on the text a person would actually see."))), /*#__PURE__*/React.createElement("div", {
    className: "hero-event",
    "aria-label": model.input_title + " REVIEW to " + model.revision + " PASS"
  }, /*#__PURE__*/React.createElement("p", {
    className: "hero-event-label"
  }, "The consequential event"), /*#__PURE__*/React.createElement("div", {
    className: "hero-event-flow"
  }, /*#__PURE__*/React.createElement("strong", null, model.input_title), /*#__PURE__*/React.createElement("span", null, "·"), /*#__PURE__*/React.createElement(Result, {
    value: "REVIEW"
  }), /*#__PURE__*/React.createElement("span", null, "→"), /*#__PURE__*/React.createElement("strong", null, model.revision), /*#__PURE__*/React.createElement("span", null, "·"), /*#__PURE__*/React.createElement(Result, {
    value: "PASS"
  }))), /*#__PURE__*/React.createElement("article", {
    className: "proof-sheet",
    "aria-label": "Annotated shelf-title proof"
  }, /*#__PURE__*/React.createElement("header", {
    className: "proof-head"
  }, /*#__PURE__*/React.createElement("span", null, "Recorded proof 01"), /*#__PURE__*/React.createElement("span", null, model.model + " · " + model.capture_date + " · Profile " + fixture.technical.policy.version)), /*#__PURE__*/React.createElement("section", {
    className: "proof-step",
    "data-proof-panel": true
  }, /*#__PURE__*/React.createElement("div", {
    className: "proof-label"
  }, /*#__PURE__*/React.createElement("span", null, "1"), "Provided title"), /*#__PURE__*/React.createElement("div", {
    className: "proof-content"
  }, /*#__PURE__*/React.createElement("h2", null, "The starting title came from the person using the tool."), /*#__PURE__*/React.createElement("p", null, "The model did not generate it. Its job began with the supplied title."), /*#__PURE__*/React.createElement("div", {
    className: "exact-string"
  }, /*#__PURE__*/React.createElement("span", null, "Provided to the agent"), /*#__PURE__*/React.createElement("code", null, model.input_title)))), /*#__PURE__*/React.createElement("section", {
    className: "proof-step",
    "data-proof-panel": true
  }, /*#__PURE__*/React.createElement("div", {
    className: "proof-label"
  }, /*#__PURE__*/React.createElement("span", null, "2"), "Contextual review"), /*#__PURE__*/React.createElement("div", {
    className: "proof-content"
  }, /*#__PURE__*/React.createElement("div", {
    className: "review-head"
  }, /*#__PURE__*/React.createElement("h2", null, "The title is valid. The adopted profile still marks the terminology for review."), /*#__PURE__*/React.createElement(Result, {
    value: evidence.first_check_status
  })), /*#__PURE__*/React.createElement("p", null, "Movie/show-family terms appear " + evidence.movie_show_family_count + " times in the public corpus; film/series-family terms appear " + evidence.series_film_family_count + ". Because both forms ship, this is REVIEW—not FAIL."), /*#__PURE__*/React.createElement("section", {
    className: "evidence-frame",
    "aria-labelledby": "terminology-observation"
  }, /*#__PURE__*/React.createElement("header", null, /*#__PURE__*/React.createElement("span", {
    id: "terminology-observation"
  }, "Public-corpus pattern"), /*#__PURE__*/React.createElement("span", null, evidence.rule_id)), /*#__PURE__*/React.createElement("div", {
    className: "evidence-grid"
  }, /*#__PURE__*/React.createElement("div", {
    className: "evidence-item"
  }, /*#__PURE__*/React.createElement("span", null, "Profile decision"), /*#__PURE__*/React.createElement("strong", null, "Human-adopted here as REVIEW")), /*#__PURE__*/React.createElement("div", {
    className: "evidence-item"
  }, /*#__PURE__*/React.createElement("span", null, "Examples retained · " + evidence.retained_counterexample_count + " of " + evidence.series_film_family_count + " occurrences"), /*#__PURE__*/React.createElement("strong", null, evidence.retained_counterexamples.join("; "))), /*#__PURE__*/React.createElement("div", {
    className: "evidence-item"
  }, /*#__PURE__*/React.createElement("span", null, "Applied scope"), /*#__PURE__*/React.createElement("strong", null, evidence.scope.when))), /*#__PURE__*/React.createElement("p", {
    className: "evidence-note"
  }, "Both terms occur in shipped titles. The profile treats the minority form as a contextual review, not an error or a violation.")))), /*#__PURE__*/React.createElement("section", {
    className: "proof-step",
    "data-proof-panel": true
  }, /*#__PURE__*/React.createElement("div", {
    className: "proof-label"
  }, /*#__PURE__*/React.createElement("span", null, "3"), "Recorded model revision"), /*#__PURE__*/React.createElement("div", {
    className: "proof-content"
  }, /*#__PURE__*/React.createElement("h2", null, "To match the adopted preference, the model changes one word."), /*#__PURE__*/React.createElement("p", null, "The recorded revision matches the one-word edit independently proposed by code."), /*#__PURE__*/React.createElement("div", {
    className: "exact-change",
    "aria-label": "Title revision"
  }, /*#__PURE__*/React.createElement("div", {
    className: "change-string"
  }, /*#__PURE__*/React.createElement("span", null, "Provided title"), /*#__PURE__*/React.createElement("code", null, first.what_changed.before)), /*#__PURE__*/React.createElement("div", {
    className: "change-arrow",
    "aria-hidden": "true"
  }, "→"), /*#__PURE__*/React.createElement("div", {
    className: "change-string"
  }, /*#__PURE__*/React.createElement("span", null, "Recorded revision"), /*#__PURE__*/React.createElement("code", null, model.revision))), /*#__PURE__*/React.createElement("p", {
    className: "model-note"
  }, model.model + " · revision authored by the model"), /*#__PURE__*/React.createElement("p", {
    className: "computation-note"
  }, "The recorded run reports the review and revision. This page independently reproduces both checks before it accepts the final title."))), /*#__PURE__*/React.createElement("section", {
    className: "proof-step",
    "data-proof-panel": true
  }, /*#__PURE__*/React.createElement("div", {
    className: "proof-label"
  }, /*#__PURE__*/React.createElement("span", null, "4"), "Checked again"), /*#__PURE__*/React.createElement("div", {
    className: "proof-content"
  }, /*#__PURE__*/React.createElement("div", {
    className: "recheck-row"
  }, /*#__PURE__*/React.createElement("h2", null, "Code checks the changed title again."), /*#__PURE__*/React.createElement(Result, {
    value: evidence.second_check_status
  })), /*#__PURE__*/React.createElement("p", null, "A prior result cannot carry forward after the text changes."), /*#__PURE__*/React.createElement("div", {
    className: "recheck-string"
  }, first.checked_again.title))), /*#__PURE__*/React.createElement("section", {
    className: "proof-step",
    "data-proof-panel": true
  }, /*#__PURE__*/React.createElement("div", {
    className: "proof-label"
  }, /*#__PURE__*/React.createElement("span", null, "5"), "Final recommendation"), /*#__PURE__*/React.createElement("div", {
    className: "proof-content"
  }, /*#__PURE__*/React.createElement("div", {
    className: "final-head"
  }, /*#__PURE__*/React.createElement("h2", null, "The checked revision becomes the recommendation."), /*#__PURE__*/React.createElement(Result, {
    value: first.checked_again.result
  })), /*#__PURE__*/React.createElement("div", {
    className: "final-recommendation"
  }, /*#__PURE__*/React.createElement("span", null, "Final recommendation"), /*#__PURE__*/React.createElement("strong", null, model.final_recommendation)), /*#__PURE__*/React.createElement("p", {
    className: "control"
  }, /*#__PURE__*/React.createElement("strong", null, "Comparison control · " + second.final_title + " remained PASS without a rewrite.")), /*#__PURE__*/React.createElement("section", {
    className: "receipt",
    "aria-label": "Technical receipt"
  }, /*#__PURE__*/React.createElement("div", {
    className: "receipt-primary"
  }, /*#__PURE__*/React.createElement("span", null, "Recorded " + model.model + " · " + model.capture_date), /*#__PURE__*/React.createElement("span", null, "Adopted demo profile " + fixture.technical.policy.version)), /*#__PURE__*/React.createElement(FullReceipt, {
    fixture: fixture
  })), /*#__PURE__*/React.createElement("p", {
    className: "boundary"
  }, "Code can enforce the adopted preference. It cannot decide whether Movies is the right creative choice for this shelf.")))))), /*#__PURE__*/React.createElement("section", {
    className: "demo-paper",
    "aria-labelledby": "system-title"
  }, /*#__PURE__*/React.createElement("div", {
    className: "paper-wrap"
  }, /*#__PURE__*/React.createElement("div", {
    className: "system-copy"
  }, /*#__PURE__*/React.createElement("h2", {
    id: "system-title"
  }, "Evidence describes the pattern. A person decides what becomes a rule."), /*#__PURE__*/React.createElement("p", null, "The Content Index describes patterns in published language. A person decides which observations become an adopted profile; code can then check against that versioned choice.")), /*#__PURE__*/React.createElement("p", {
    className: "continuity"
  }, "This public proof isolates one mechanism from my broader language-governance work: people adopt the standard, agents generate, and code checks the final text. ", /*#__PURE__*/React.createElement("a", {
    href: "../index.html#verso"
  }, "See the Verso case study.")), /*#__PURE__*/React.createElement("nav", {
    className: "demo-doors",
    "aria-label": "Supporting evidence"
  }, /*#__PURE__*/React.createElement("a", {
    className: "demo-door",
    href: "./evidence.html"
  }, "Read the evidence paper"), /*#__PURE__*/React.createElement("a", {
    className: "demo-door",
    href: "./demo_fixture.json"
  }, "View the generated receipt"), /*#__PURE__*/React.createElement("a", {
    className: "demo-door",
    href: "./recorded_agent_trace.json"
  }, "Inspect the recorded exchange")), /*#__PURE__*/React.createElement("p", {
    className: "demo-note"
  }, "This independent demonstration uses patterns observed in public Netflix shelf titles and is not affiliated with Netflix."))));
}
function App() {
  const [fixture, setFixture] = React.useState(null);
  const [failed, setFailed] = React.useState(false);
  React.useEffect(() => {
    fetch("./demo_fixture.json").then(response => {
      if (!response.ok) throw new Error("fixture unavailable");
      return response.json();
    }).then(value => {
      if (!validateFixture(value)) throw new Error("fixture invalid");
      setFixture(value);
    }).catch(() => setFailed(true));
  }, []);
  if (failed) return /*#__PURE__*/React.createElement("div", {
    className: "demo-loading"
  }, "The proof could not load its generated fixture. The supporting evidence remains available from this directory.");
  if (!fixture) return /*#__PURE__*/React.createElement("div", {
    className: "demo-loading"
  }, "Loading the exact-string proof…");
  return /*#__PURE__*/React.createElement(Demo, {
    fixture: fixture
  });
}
ReactDOM.createRoot(document.getElementById("root")).render(/*#__PURE__*/React.createElement(App, null));
})();
