/* Generated by tools/build-static.js — compiled ahead of time, do not edit. */

/* ---- plays/papers/naming-grammar (inline script) ---- */
(function () {
const {
  Report,
  ReportSection,
  DocFigure,
  NoteRef,
  Endnotes,
  References,
  Finding,
  DataTable,
  IndexRows,
  RuleSplit,
  Ledger,
  PullQuote,
  ResearchGrid,
  ProvenanceNote
} = window.CalebStacyPortfolioDesignSystem_4a3883;

/* ---------- formatting only — every number below is read from grammar.json / corpus.json at
   runtime; nothing here is a measurement ---------- */

const isLookupSlot = s => s.kind.indexOf("closed") !== -1 || s.kind === "structural";

/* ---------- app ---------- */

function App() {
  const [grammar, setGrammar] = React.useState(null);
  const [corpus, setCorpus] = React.useState(null);
  const [error, setError] = React.useState(null);
  React.useEffect(() => {
    Promise.all([fetch("./grammar.json").then(r => {
      if (!r.ok) throw new Error("grammar.json HTTP " + r.status);
      return r.json();
    }), fetch("./corpus.json").then(r => {
      if (!r.ok) throw new Error("corpus.json HTTP " + r.status);
      return r.json();
    })]).then(([g, c]) => {
      setGrammar(g);
      setCorpus(c);
    }).catch(e => setError(e.message || String(e)));
  }, []);
  if (error) {
    return /*#__PURE__*/React.createElement("div", {
      className: "errbox"
    }, "Could not load the data files (", error, "). Every number on this page is computed at runtime from ", /*#__PURE__*/React.createElement("code", null, "grammar.json"), " and ", /*#__PURE__*/React.createElement("code", null, "corpus.json"), ". Open this page over a local server, not as a bare file.");
  }
  if (!grammar || !corpus) {
    return /*#__PURE__*/React.createElement("div", {
      className: "errbox"
    }, "Loading grammar.json and corpus.json…");
  }
  const tudumPages = corpus.tudum.length;
  const discordPages = corpus.discord_blog.length;
  const tudumFromTitle = corpus.tudum.filter(r => r.source === "title_fallback").length;
  const discordFromTitle = corpus.discord_blog.filter(r => r.source === "title_fallback").length;
  const discordExcluded = corpus.discord_blog.filter(r => r.excluded_reason).length;
  const cov = grammar.coverage;
  const openSlots = grammar.slots.filter(s => !isLookupSlot(s));
  const closedSlots = grammar.slots.filter(isLookupSlot);
  const ruleSplitRules = grammar.slots.map(s => ({
    kind: isLookupSlot(s) ? "code" : "model",
    rule: s.id + " · " + s.name
  }));
  const tudumFamilyRows = grammar.families.tudum.slice().sort((a, b) => b.count - a.count).map(f => [f.name, String(f.count), f.pct + "%", (f.template || []).some(t => t.slot === "COLON_CLAUSE" || t.slot === "TITLE" || t.slot === "GENRE_PUN_VERB" || t.slot === "COUNT" || t.slot === "SUPERLATIVE" || t.slot === "CONNECTOR_VP") ? "yes" : "no"]);
  const discordFamilyRows = grammar.families.discord_blog.slice().sort((a, b) => b.count - a.count).map(f => [f.name, String(f.count), f.pct + "%"]);
  const generatedItems = grammar.families.tudum.flatMap(f => (f.generated_novel || []).map(g => ({
    id: f.name + " · " + g.verdict,
    asserts: g.text,
    meta: g.why ? [g.why] : undefined
  })));
  const chunk = (arr, n) => {
    const out = [];
    for (let i = 0; i < arr.length; i += n) out.push(arr.slice(i, i + n));
    return out;
  };
  const generatedChunks = chunk(generatedItems, 8);
  const sl = grammar.seo_title_layer;
  const facetRows = sl.facet_vocabulary.map(f => [f.facet, String(f.count)]);
  const pairRows = sl.example_pairs.map(p => [p.h1, p.title]);
  const cc = grammar.control_comparison;
  const sharedRows = cc.shared_rules.map(r => [r.rule, r.tudum, r.discord, r.reading]);
  return /*#__PURE__*/React.createElement(Report, {
    title: "A naming grammar for Tudum headlines",
    runningHead: "A naming grammar for Tudum headlines — working paper",
    status: "Working paper",
    author: "Caleb Stacy",
    date: "25 July 2026",
    plain: /*#__PURE__*/React.createElement("p", {
      style: {
        margin: 0
      }
    }, "Most Tudum headlines aren't written from scratch. A small number of reusable templates account for roughly two out of every three of them. This paper maps those templates: what part of a headline is a fixed word, what part is filled in fresh each time, and which combinations Tudum does and doesn't use. Discord's blog headlines go through the identical process as a control, to separate what's just how entertainment headline-writing works in general from what's actually specific to Netflix."),
    subtitle: "240 Tudum headlines reverse-engineered into a slot-and-fill grammar, with 197 Discord blog headlines run through the same method as a control.",
    abstract: /*#__PURE__*/React.createElement("p", {
      style: {
        margin: 0
      }
    }, "This is a different exercise from a voice measurement. It derives the productive rules that generate a family of headlines: an inventory of fill-in positions, which are obligatory, which draw from a small closed list versus an open one, and which co-occur. Handed to a person or a writing tool, this is what you'd generate against. Netflix's actual personalised shelf titles sit behind a login and were not accessed for this. Tudum's public editorial headlines do an adjacent job (classify, entice, set an expectation) and are readable without an account.")
  }, /*#__PURE__*/React.createElement(ReportSection, {
    id: "corpus",
    title: "What was collected, and what wasn't"
  }, /*#__PURE__*/React.createElement(Finding, {
    measured: tudumPages + " Tudum headlines · " + discordPages + " Discord blog pages collected, " + (discordPages - discordExcluded) + " usable",
    verdict: "corpus"
  }, "240 Tudum pages and 200 Discord blog pages, one headline per page. Always the headline actually on the page, not the one in the browser tab. On Tudum those two are almost never the same sentence, which turns out to be its own finding further down."), /*#__PURE__*/React.createElement(DocFigure, {
    caption: "Where each collected headline actually came from.",
    source: "corpus.json"
  }, /*#__PURE__*/React.createElement(Ledger, {
    label: "Headline source",
    items: [{
      value: String(tudumPages - tudumFromTitle),
      label: "Tudum headlines from the page's own heading"
    }, {
      value: String(tudumFromTitle),
      label: "Tudum headlines from the tab title (no on-page heading existed)"
    }, {
      value: String(discordPages - discordFromTitle - discordExcluded),
      label: "Discord headlines from the page's own heading"
    }, {
      value: String(discordFromTitle),
      label: "Discord headlines from the tab title"
    }]
  })), /*#__PURE__*/React.createElement(ProvenanceNote, {
    label: "Shelf-title exclusion"
  }, "Netflix's actual in-product shelf titles (the row names on the personalised home screen) sit behind a login and were not accessed, scraped, or reconstructed for this analysis. Tudum's public editorial headlines are the substitute: a different surface doing an adjacent job, publicly readable without an account. That substitution is a real limit of this piece, stated plainly.", /*#__PURE__*/React.createElement(NoteRef, null)), /*#__PURE__*/React.createElement(ProvenanceNote, {
    label: "Excluded as collection artifacts"
  }, discordExcluded, " of ", discordPages, " collected Discord pages yielded no usable headline. The on-page heading captured was site navigation text (\"Discord Blog\"), not the article's own title, most likely because the real headline had not finished loading when the page was captured. These are excluded from every count on this page rather than counted as unexplained. They aren't real headlines the analysis failed to explain; they're a gap in what was captured.")), /*#__PURE__*/React.createElement(ReportSection, {
    id: "slots",
    title: "The vocabulary every headline is built from"
  }, /*#__PURE__*/React.createElement(Finding, {
    measured: grammar.slots.length + " slots · " + closedSlots.length + " lookup · " + openSlots.length + " judgment",
    verdict: "vocabulary"
  }, "Every headline family below is built from the same seventeen fill-in positions. Most draw from a short, fixed list of words short enough to hand a generator outright. A few are written fresh every single time, because no fixed list would produce them correctly. Most obviously that's the show's own title, and the one slot examined closely in \"The one rule that isn't a lookup\" below."), /*#__PURE__*/React.createElement(DocFigure, {
    caption: "The slots where a person or a model still has to write something, because no fixed list would fill these correctly.",
    source: "grammar.json · slots, kind=open"
  }, /*#__PURE__*/React.createElement(IndexRows, {
    label: "Open: judgment",
    rows: openSlots.map(s => ({
      id: s.id,
      asserts: s.description,
      meta: [s.kind, "e.g. " + s.example_fills.slice(0, 3).join(" / ")]
    }))
  })), /*#__PURE__*/React.createElement(DocFigure, {
    caption: "The slots a short, fixed list can fill on its own.",
    source: "grammar.json · slots, kind=closed/semi-closed/structural"
  }, /*#__PURE__*/React.createElement(IndexRows, {
    label: "Closed: lookup",
    rows: closedSlots.map(s => ({
      id: s.id,
      asserts: s.description,
      meta: [s.kind, "e.g. " + s.example_fills.slice(0, 3).join(" / ")]
    }))
  })), /*#__PURE__*/React.createElement(DocFigure, {
    caption: "The same seventeen slots, sorted by whether a short list can fill them or a person still has to write something.",
    source: "grammar.json · slots, sorted by fill behaviour"
  }, /*#__PURE__*/React.createElement(RuleSplit, {
    rules: ruleSplitRules,
    modelLabel: "Open: judgment",
    codeLabel: "Closed: lookup",
    note: "A generator built on this schema can safely auto-fill the right-hand column from the lists above. The left-hand column is where a person or a model still has to write something: most obviously the show's title, the free clause after a colon, and the pun-verb slot examined next."
  }))), /*#__PURE__*/React.createElement(ReportSection, {
    id: "families",
    title: "How Tudum actually combines them"
  }, /*#__PURE__*/React.createElement(Finding, {
    measured: cov.tudum.classified + " of " + cov.tudum.total + " (" + cov.tudum.pct + "%) explained by " + grammar.families.tudum.length + " named families",
    verdict: "templated"
  }, "Eleven named templates explain roughly two out of every three Tudum headlines. The most common is a plain \"name it, then say something about it\" pattern; the most rigid changes only two show names week to week and nothing else."), /*#__PURE__*/React.createElement(DocFigure, {
    kind: "table",
    wide: true,
    caption: "Every named Tudum headline family, most common first.",
    source: "grammar.json · families.tudum"
  }, /*#__PURE__*/React.createElement(DataTable, {
    variant: "meta",
    columns: ["Family", "Count", "Share of corpus", "Has an open slot"],
    rows: tudumFamilyRows
  })), /*#__PURE__*/React.createElement("p", {
    style: {
      margin: "0 0 1em"
    }
  }, "To check whether the rules actually generate, every family was used to write new headlines that were never in the source collection, including, honestly, the ones that come out wrong. All ", generatedItems.length, " generated examples are below, in three groups, not a curated best case. Each row is labelled family · verdict, with the reasoning underneath where there is any.", /*#__PURE__*/React.createElement(NoteRef, null)), generatedChunks.map((chunk, i) => /*#__PURE__*/React.createElement(DocFigure, {
    key: i,
    caption: "Headlines generated straight from the rules above, with an honest verdict on each (" + (i + 1) + " of " + generatedChunks.length + "), including where the grammar breaks.",
    source: "grammar.json · families.tudum[].generated_novel"
  }, /*#__PURE__*/React.createElement(IndexRows, {
    label: "Generated · part " + (i + 1),
    rows: chunk
  })))), /*#__PURE__*/React.createElement(ReportSection, {
    id: "interesting",
    title: "The one rule that isn't a lookup"
  }, /*#__PURE__*/React.createElement(Finding, {
    verdict: "judgment, not lookup"
  }, "Every other slot in this grammar reduces to a short list of words you could hand a generator. One doesn't: the verb in a weekly ranking headline is picked fresh each time to pun on what that specific show is actually about. A detective story \"Cracks the Case.\" A heist thriller \"Confiscates the No. 1 Spot.\" To fill this slot correctly you have to know what the show is about. A list of ranking-appropriate verbs alone won't do it."), /*#__PURE__*/React.createElement(PullQuote, {
    attribution: "Eight weekly-ranking headlines, eight different verbs, never reused"
  }, "A missing-persons thriller \"Chases Down No. 1.\" A frontier family drama \"Journeys to No. 1.\" A workplace romance \"Enamors Viewers.\" The verb is coined fresh every time and is never reused across two different titles in this corpus."), /*#__PURE__*/React.createElement("p", {
    style: {
      margin: "var(--space-7) 0 0"
    }
  }, "This is also the clearest place the grammar breaks as a pure generator: a grammatically perfect fill from a generic verb (\"Takes No. 1\") is exactly the kind of fill this family's eight real examples never use. Getting this slot right needs a one-line description of what the show is about as an input, not just a word list. That makes it a genuinely different, harder kind of rule than every other slot in this corpus.")), /*#__PURE__*/React.createElement(ReportSection, {
    id: "seo",
    title: "Every Tudum page writes two headlines"
  }, /*#__PURE__*/React.createElement(Finding, {
    measured: "Tudum " + sl.tudum_diverge_pct + "% diverge · Discord " + sl.discord_diverge_pct + "% diverge",
    verdict: "separates"
  }, "On ", sl.tudum_diverge_pct, "% of Tudum pages, the headline on the page and the headline in the browser tab are genuinely different sentences: not just re-capitalised, actually different wording aimed at a different reader. On Discord's blog the two match on essentially every page."), /*#__PURE__*/React.createElement(DocFigure, {
    kind: "table",
    caption: "How often the on-page headline and the browser-tab headline diverge, on pages that have both.",
    source: "grammar.json · seo_title_layer"
  }, /*#__PURE__*/React.createElement(DataTable, {
    variant: "meta",
    columns: ["Site", "Diverge", "Of h1-bearing pages"],
    rows: [["Tudum", sl.tudum_diverge_pct + "%", sl.tudum_diverge_count + " / " + sl.tudum_h1_bearing_pages], ["Discord blog", sl.discord_diverge_pct + "%", sl.discord_diverge_count + " / " + sl.discord_h1_bearing_pages]]
  })), /*#__PURE__*/React.createElement(DocFigure, {
    kind: "table",
    wide: true,
    caption: "Six Tudum pages, both headlines side by side.",
    source: "grammar.json · seo_title_layer.example_pairs"
  }, /*#__PURE__*/React.createElement(DataTable, {
    variant: "meta",
    columns: ["On the page (<h1>)", "In the browser tab (<title>)"],
    rowHeader: false,
    rows: pairRows
  })), /*#__PURE__*/React.createElement(DocFigure, {
    kind: "table",
    caption: "What the browser-tab headline is actually made of, across all 240 Tudum pages: a comma-separated list of facets, not a written sentence.",
    source: "grammar.json · seo_title_layer.facet_vocabulary"
  }, /*#__PURE__*/React.createElement(DataTable, {
    variant: "meta",
    columns: ["Facet", "Appears in N of 240 tab titles"],
    rows: facetRows
  }))), /*#__PURE__*/React.createElement(ReportSection, {
    id: "discord",
    title: "The same method, run on a company that isn't selling entertainment"
  }, /*#__PURE__*/React.createElement(Finding, {
    measured: cov.discord_blog.classified + " of " + cov.discord_blog.total + " (" + cov.discord_blog.pct + "%) explained by " + grammar.families.discord_blog.length + " named families",
    verdict: "control"
  }, "Run the identical process on Discord's blog and eight different templates show up, more spread out than Tudum's. A software company's blog spans engineering explainers, release notes, shop promos, and staff picks, a much wider range of writing jobs than an entertainment hub covers."), /*#__PURE__*/React.createElement(DocFigure, {
    kind: "table",
    wide: true,
    caption: "Every named Discord blog headline family, most common first.",
    source: "grammar.json · families.discord_blog"
  }, /*#__PURE__*/React.createElement(DataTable, {
    variant: "meta",
    columns: ["Family", "Count", "Share of analysed corpus"],
    rows: discordFamilyRows
  }))), /*#__PURE__*/React.createElement(ReportSection, {
    id: "compare",
    title: "What's shared, and what's brand-specific"
  }, /*#__PURE__*/React.createElement(Finding, {
    verdict: "control comparison"
  }, "Some headline habits show up on both sites at close to the same rate. Those are probably just how editorial headline-writing works, not something either company invented. Others only make sense for one of the two: writing a ranking headline needs a weekly popularity chart, and writing a changelog needs a piece of software to log changes to."), /*#__PURE__*/React.createElement(DocFigure, {
    kind: "table",
    wide: true,
    caption: "Habits present on both sites at comparable rates.",
    source: "grammar.json · control_comparison.shared_rules"
  }, /*#__PURE__*/React.createElement(DataTable, {
    variant: "meta",
    columns: ["Habit", "Tudum", "Discord blog", "Reading"],
    rows: sharedRows
  })), /*#__PURE__*/React.createElement("div", {
    className: "ng-cols",
    style: {
      marginTop: "var(--space-8)"
    }
  }, /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement("p", {
    style: {
      margin: "0 0 8px",
      fontFamily: "var(--font-mono)",
      fontSize: 9,
      fontWeight: 700,
      color: "var(--story-muted)"
    }
  }, "Netflix / Tudum only: needs a streaming catalogue to make sense"), /*#__PURE__*/React.createElement("ul", {
    className: "ng-plain-list"
  }, cc.netflix_specific_rules.map((r, i) => /*#__PURE__*/React.createElement("li", {
    key: i
  }, r)))), /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement("p", {
    style: {
      margin: "0 0 8px",
      fontFamily: "var(--font-mono)",
      fontSize: 9,
      fontWeight: 700,
      color: "var(--story-muted)"
    }
  }, "Discord only: needs a software product to make sense"), /*#__PURE__*/React.createElement("ul", {
    className: "ng-plain-list"
  }, cc.discord_specific_rules.map((r, i) => /*#__PURE__*/React.createElement("li", {
    key: i
  }, r)))))), /*#__PURE__*/React.createElement(ReportSection, {
    id: "residue",
    title: "What the grammar doesn't explain, and why that's not a gap"
  }, /*#__PURE__*/React.createElement(Finding, {
    measured: "Tudum " + cov.tudum.residue + " (" + cov.tudum.residue_pct + "%) · Discord " + cov.discord_blog.residue + " (" + cov.discord_blog.residue_pct + "%) unexplained",
    verdict: "not a shortfall"
  }, "About three in ten Tudum headlines, and about one in four of Discord's, don't fit any named template. That's not a failure of this analysis. Templated pages (a cast list, a trailer drop, a weekly ranking) really are formulaic. One-off news writing about a specific event is hand-written on purpose: a news headline that read like a template would undersell the news."), /*#__PURE__*/React.createElement("div", {
    className: "ng-cols"
  }, /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement("p", {
    style: {
      margin: "0 0 8px",
      fontFamily: "var(--font-mono)",
      fontSize: 9,
      fontWeight: 700,
      color: "var(--story-muted)"
    }
  }, "Sample: Tudum residue"), /*#__PURE__*/React.createElement("ul", {
    className: "ng-plain-list"
  }, grammar.residue.tudum.sample.slice(0, 8).map((h, i) => /*#__PURE__*/React.createElement("li", {
    key: i
  }, h)))), /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement("p", {
    style: {
      margin: "0 0 8px",
      fontFamily: "var(--font-mono)",
      fontSize: 9,
      fontWeight: 700,
      color: "var(--story-muted)"
    }
  }, "Sample: Discord residue"), /*#__PURE__*/React.createElement("ul", {
    className: "ng-plain-list"
  }, grammar.residue.discord_blog.sample.slice(0, 8).map((h, i) => /*#__PURE__*/React.createElement("li", {
    key: i
  }, h)))))), /*#__PURE__*/React.createElement(ReportSection, {
    id: "grounding",
    title: "This has a name in linguistics"
  }, /*#__PURE__*/React.createElement(Finding, {
    verdict: "grounded, not invented"
  }, "Treating a recurring headline shape as a fixed frame with blanks to fill in is a described idea in linguistics, not something invented for this page. It's the same move researchers make on ordinary sentences, applied here to a kind of writing with an unusually high template rate."), /*#__PURE__*/React.createElement(DocFigure, {
    caption: "What each cited source makes computable here.",
    source: "See References"
  }, /*#__PURE__*/React.createElement(ResearchGrid, {
    items: [{
      source: "Fillmore, Kay & O'Connor",
      year: "1988",
      gives: "Fixed frames as real grammar units",
      note: "Showed that a fixed frame with open slots is a unit of grammar in its own right, not just words plugged into ordinary sentence structure. That's the basis for calling each family here a rule rather than a habit."
    }, {
      source: "Goldberg, Adele E.",
      year: "1995",
      gives: "Form-meaning pairings with slots",
      note: "The core claim behind Construction Grammar: a pattern is learned and stored as a whole, with blanks, independent of the words that fill it. That's directly the shape a “family” takes on this page."
    }, {
      source: "Bell, Allan",
      year: "1991",
      gives: "Headline writing as its own studied register",
      note: "News headlines have long been described as a formulaic sub-language distinct from body text. This corpus is that register at an unusually high density."
    }, {
      source: "Biber, Douglas",
      year: "1988",
      gives: "Comparing one corpus's forms against a second",
      note: "The method behind the whole control comparison: find a corpus's own recurring forms, then compare against a second corpus to see what's general versus source-specific."
    }]
  }))), /*#__PURE__*/React.createElement(ReportSection, {
    id: "verdict",
    title: "Descriptive, not prescriptive"
  }, /*#__PURE__*/React.createElement(Finding, {
    verdict: "descriptive"
  }, "Nothing on this page is a recommendation for how Netflix or Discord should name anything. Both companies' naming choices are read here as evidence of a working system, not a problem to fix. The residue sections in particular are a real property of how each publisher's editorial output actually splits between templated and one-off writing, not an incompleteness in the analysis."), /*#__PURE__*/React.createElement(ProvenanceNote, {
    label: "Reproducibility"
  }, grammar.method.reproducibility)), /*#__PURE__*/React.createElement(Endnotes, {
    notes: ["Netflix's personalised in-product shelf titles were never accessed, logged into, or reconstructed for this piece; Tudum's public editorial headlines are a different surface doing an adjacent job, not a stand-in verified to behave identically.", "The genre filter that keeps how-to and FAQ content out of the Tudum sample works only by reading each page's own declared category. It will not catch a genre-atypical article Tudum did not tag as such. A disclosed limit of a metadata-based filter, not a claim that every non-editorial page was caught.", "The 24 generated examples above were written directly from the rules and never checked against the live source collection for accidental overlap; “plausible” means consistent with the rule, not confirmed absent from the corpus."]
  }), /*#__PURE__*/React.createElement(References, {
    items: [{
      text: "Fillmore, C. J., Kay, P., & O'Connor, M. C. (1988). Regularity and idiomaticity in grammatical constructions: The case of let alone. Language, 64(3), 501–538."
    }, {
      text: "Goldberg, A. E. (1995). Constructions: A Construction Grammar Approach to Argument Structure. University of Chicago Press."
    }, {
      text: "Bell, A. (1991). The Language of News Media. Blackwell."
    }, {
      text: "Biber, D. (1988). Variation across Speech and Writing. Cambridge University Press."
    }]
  }));
}
ReactDOM.createRoot(document.getElementById("root")).render(/*#__PURE__*/React.createElement(App, null));
})();
